"use client";
import {useState} from "react";import Link from "next/link";import {countries} from "../data";
const metrics=[{label:"Population",key:"population",format:(n:number)=>n>=1e9?`${(n/1e9).toFixed(2)}B`:`${(n/1e6).toFixed(1)}M`},{label:"Land area",key:"area",format:(n:number)=>`${(n/1e6).toFixed(2)}M km²`}];
export default function CompareTool(){const [first,setFirst]=useState("nigeria");const [second,setSecond]=useState("japan");const a=countries.find(c=>c.slug===first)!;const b=countries.find(c=>c.slug===second)!;return <>
  <div className="compare-selectors"><label><span>Country A</span><select value={first} onChange={e=>setFirst(e.target.value)}>{countries.filter(c=>c.slug!==second).map(c=><option value={c.slug} key={c.slug}>{c.flag} {c.name}</option>)}</select></label><i>VERSUS</i><label><span>Country B</span><select value={second} onChange={e=>setSecond(e.target.value)}>{countries.filter(c=>c.slug!==first).map(c=><option value={c.slug} key={c.slug}>{c.flag} {c.name}</option>)}</select></label></div>
  <div className="compare-head"><div style={{"--country":a.color} as React.CSSProperties}><span>{a.flag}</span><small>{a.subregion}</small><h2>{a.name}</h2><Link href={`/countries/${a.slug}`}>View profile ↗</Link></div><div style={{"--country":b.color} as React.CSSProperties}><span>{b.flag}</span><small>{b.subregion}</small><h2>{b.name}</h2><Link href={`/countries/${b.slug}`}>View profile ↗</Link></div></div>
  <div className="comparison-table"><div className="comparison-row text"><p>Capital</p><b>{a.capital}</b><b>{b.capital}</b></div>{metrics.map(m=>{const av=a[m.key as 'population'|'area'],bv=b[m.key as 'population'|'area'],max=Math.max(av,bv);return <div className="comparison-row" key={m.label}><p>{m.label}</p><div><b>{m.format(av)}</b><i style={{width:`${av/max*100}%`,background:a.color}}/></div><div><b>{m.format(bv)}</b><i style={{width:`${bv/max*100}%`,background:b.color}}/></div></div>})}{[["Population density",a.density,b.density],["Nominal GDP",a.gdp,b.gdp],["Life expectancy",a.lifeExpectancy,b.lifeExpectancy],["Internet access",a.internet,b.internet],["Government",a.government,b.government],["Currency",a.currency,b.currency]].map(row=><div className="comparison-row text" key={row[0]}><p>{row[0]}</p><b>{row[1]}</b><b>{row[2]}</b></div>)}</div>
  </>
}
