import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync,mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {handleTripsApi} from '../worker/trips-api.ts';
const adapter=sqlite=>({prepare(sql){const stmt=sqlite.prepare(sql);let values=[];return{bind(...v){values=v;return this;},async all(){return{results:stmt.all(...values)};},async run(){return{meta:{changes:stmt.run(...values).changes}};}};}});
const req=(path,method='GET',body,owner='owner-a',extra={})=>new Request('https://terra.test'+path,{method,headers:{...(owner?{'oai-authenticated-user-id':owner}:{}),...(body?{'Content-Type':'application/json'}:{}),...extra},body:body?JSON.stringify(body):undefined});
test('travel brief and manual itinerary persist and remain private to their owner',async()=>{const dir=mkdtempSync(join(tmpdir(),'terrascope-'));let sqlite=new DatabaseSync(join(dir,'trips.sqlite'));sqlite.exec(readFileSync(new URL('../drizzle/0000_early_blacklash.sql',import.meta.url),'utf8'));let db=adapter(sqlite);try{
 assert.equal((await handleTripsApi(req('/api/trips','GET',undefined,null),db)).status,401);assert.equal((await handleTripsApi(req('/api/trips'))).status,503);
 const brief={id:crypto.randomUUID(),destination:'Nigeria',city:'Abuja',startDate:'2026-10-10',endDate:'2026-10-12',travelers:2,budget:'150000.50',currency:'NGN',interests:'Museums and food',notes:'Relaxed pace',itinerary:'Day 1 · 2026-10-10: Jabi Lake. Estimated group allowance ₦20000.'};
 assert.equal((await handleTripsApi(req('/api/trips','POST',brief),db)).status,201);assert.equal((await handleTripsApi(req('/api/trips','POST',brief),db)).status,200);assert.equal((await handleTripsApi(req('/api/trips','POST',brief,'owner-b'),db)).status,409);
 assert.equal((await handleTripsApi(req('/api/trips','POST',{...brief,id:crypto.randomUUID(),endDate:'2026-10-01'}),db)).status,400);assert.equal((await handleTripsApi(req('/api/trips','POST',{...brief,id:crypto.randomUUID(),travelers:1.5}),db)).status,400);
 assert.equal((await (await handleTripsApi(req('/api/trips'),db)).json()).trips[0].itinerary,brief.itinerary);
 assert.equal((await handleTripsApi(req('/api/trips','POST',{...brief,itinerary:'Changed payload'}),db)).status,409);
 assert.equal((await handleTripsApi(req('/api/trips/'+brief.id,'PUT',{itinerary:'Do not allow this'},'owner-b'),db)).status,404);
 assert.equal((await handleTripsApi(req('/api/trips/'+brief.id,'PUT',{itinerary:'Day 1: Museum. Day 2: Food tour.'}),db)).status,200);
 assert.equal((await handleTripsApi(req('/api/trips/'+brief.id,'PUT',{itinerary:'Blocked'},'owner-a',{origin:'https://other.test'}),db)).status,403);
 sqlite.close();sqlite=new DatabaseSync(join(dir,'trips.sqlite'));db=adapter(sqlite);const trips=(await (await handleTripsApi(req('/api/trips'),db)).json()).trips;assert.equal(trips.length,1);assert.equal(trips[0].budget_minor,15000050);assert.equal(trips[0].itinerary,'Day 1: Museum. Day 2: Food tour.');assert.equal((await (await handleTripsApi(req('/api/trips','GET',undefined,'owner-b'),db)).json()).trips.length,0);
 }finally{sqlite.close();rmSync(dir,{recursive:true,force:true});}});
