import {populationDataset,populationByCode} from "../population-data";
import {indicatorDataset,indicatorsByCode} from "../country-indicators";
import {cityGuides,curatedFactsByCode,notablePeopleByCode} from "../country-content";
import {funCatalogue} from "../fun-activities";
import {leadershipSources,leadershipCheckedAt} from "../leadership-sources";
import {SiteHeader} from "../components/SiteHeader";
import {SiteFooter} from "../components/SiteFooter";

const chapters = [
  {number:"01",label:"Built",title:"One atlas, 195 different stories.",text:"I built a country-by-country encyclopaedia that connects geography, people, sport, culture, travel and rankings without making each profile feel like a copy of the last one. The goal was simple: let someone arrive for a number and stay because the place feels worth knowing."},
  {number:"02",label:"Learned",title:"Clean data is rarely born clean.",text:"Working across 195 countries taught me that even basic facts arrive in different formats, years and definitions. I learned to normalise country codes, names, currencies, languages and units, then keep editorial writing separate from structured statistics so both can grow without breaking the site."},
  {number:"03",label:"Challenge",title:"Consistency without pretending certainty.",text:"The hardest part was sourcing comparable information. Population estimates move, borders can be politically sensitive, leaders change and rankings use different dates. I had to decide what counted, keep the source and year visible, and leave room for context instead of presenting every figure as permanent truth."},
];

export default function MethodPage(){return <main><SiteHeader active="method"/>
  <section className="method-hero"><p>About the project · Method & making</p><div><h1>A living atlas,<br/><em>built with care.</em></h1><div><span>Why I made it</span><blockquote>“I wanted to build something that makes the world feel explorable—not another Wikipedia clone you open, skim and forget.”</blockquote><p>— Favour Imegu, creator of TerraScope</p></div></div></section>
  <section className="build-story"><header><span>Behind TerraScope</span><h2>Built / Learned / Challenge</h2></header><div>{chapters.map((chapter)=><article key={chapter.label}><span>{chapter.number}</span><small>{chapter.label}</small><h3>{chapter.title}</h3><p>{chapter.text}</p></article>)}</div></section>
  <section className="method-principles"><p>How the atlas stays honest</p><div><article><b>Source beside the claim</b><span>Important rankings keep the publisher, date and definition visible.</span></article><article><b>Context before judgement</b><span>A ranking is a lens—not a verdict on a country or its people.</span></article><article><b>Structured, then human</b><span>Data provides the backbone; clear editorial writing makes it worth exploring.</span></article></div></section>
  <section id="data-register" className="data-register"><p className="eyebrow">Source editions & coverage</p><h2>Know what you’re reading.</h2><p>Data refresh: {indicatorDataset.refreshedAt}. A retrieval date is different from the year measured. Geographic coverage is complete; editorial depth and venue verification vary.</p><div className="register-scroll"><table><thead><tr><th>Record</th><th>Coverage / edition</th><th>Source and limits</th></tr></thead><tbody>
  <tr><td>Population</td><td>{Object.keys(populationByCode).length} countries · refreshed {populationDataset.refreshedAt}</td><td><a href={populationDataset.worldBankUrl}>World Bank SP.POP.TOTL</a>; <a href={populationDataset.vaticanUrl}>Vatican City’s 2024 resident count</a>. Every profile shows the observation year. Dashboard world total is the World Bank WLD observation.</td></tr>
  <tr><td>Economy, health & connectivity</td><td>{Object.keys(indicatorsByCode).length} countries have at least one metric</td><td>{Object.entries(indicatorDataset.sources).map(([key,source])=><div key={key}><a href={source.url}>{source.indicator}</a> · publisher updated {source.lastUpdated} · {Object.values(indicatorsByCode).filter(row=>row[key as keyof typeof row]).length} country records</div>)} GDP uses current US dollars; internet use is a share of population. Missing records are not filled with estimates.</td></tr>
  <tr><td>Geography</td><td>195 sovereign states · world-countries / IANA-linked time zones</td><td><a href="https://github.com/mledoze/countries">Reference dataset</a>. Area is total area, not land-only area. Countries can span multiple time zones. Territorial definitions differ across publishers.</td></tr>
  <tr><td>Country facts & people</td><td>{Object.keys(curatedFactsByCode).length} curated fact files; {Object.keys(notablePeopleByCode).length} editorial people files</td><td>Other profiles use 10 structured atlas facts. A country without a curated person or football record displays a missing-record notice.</td></tr>
  <tr><td>Travel & Fun</td><td>195 country travel files · {cityGuides.length} detailed city guides · {funCatalogue.length} fun activity types</td><td>Country planning starters offer ideas without asserting local venue availability. <a href="https://sipandpaint.ng/">Sip and Paint NG</a> and <a href="https://www.linkedin.com/company/genesis-cinemas-limited/">Genesis Cinemas</a> provider lists checked 2026-09-30. All planner costs are user-editable assumptions. Confirm quotes, opening times, age rules and transport.</td></tr>
  <tr><td>Football</td><td>Men’s ranking: 20 July 2026; World Cup titles through 2026</td><td><a href="https://inside.fifa.com/fifa-rankings/world-ranking/men/news/spain-top-mens-world-rankings-after-second-world-cup">FIFA official release</a>. Other country dossiers and biographies are selected historical highlights, not complete squads, transfer lists or honours databases.</td></tr>
  <tr><td>Other ranking snapshots</td><td>Tourism: 2024 · IQ-test dataset: 2025 · CPI: 2025</td><td>These retain their original editions. Tourism counts overnight international arrivals. Online IQ-test respondents are self-selected and do not establish national intelligence. CPI measures perceived public-sector corruption.</td></tr>
<tr><td>Leadership</td><td>{Object.keys(leadershipSources).length} featured official references · checked {leadershipCheckedAt}</td><td>Each featured profile links its official reference. These are dated snapshots; other countries do not receive an unverified office-holder.</td></tr>
  <tr><td>Current reference corrections</td><td>Reviewed 2026-09-30</td><td><a href="https://economy-finance.ec.europa.eu/euro/eu-countries-and-euro/bulgaria-and-euro_en">Bulgaria’s euro adoption</a>; <a href="https://www.gov.za/news/speeches/president-cyril-ramaphosa-signing-ceremony-south-african-sign-language-bill-19-jul">South Africa’s 12th official language</a>; <a href="https://www.whitehouse.gov/presidential-actions/2025/03/designating-english-as-the-official-language-of-the-united-states/">US language executive order</a>.</td></tr>
  </tbody></table></div></section>
  <SiteFooter/></main>}
