import {SiteHeader} from "../components/SiteHeader";
import {SiteFooter} from "../components/SiteFooter";
import {governmentAsOfLabel} from "../government-data";

const chapters = [
  {number:"01",label:"Built",title:"One atlas, 195 different stories.",text:"I built a country-by-country encyclopaedia that connects geography, people, sport, culture, travel and rankings without making each profile feel like a copy of the last one. The goal was simple: let someone arrive for a number and stay because the place feels worth knowing."},
  {number:"02",label:"Learned",title:"Clean data is rarely born clean.",text:"Working across 195 countries taught me that even basic facts arrive in different formats, years and definitions. I learned to normalise country codes, names, currencies, languages and units, then keep editorial writing separate from structured statistics so both can grow without breaking the site."},
  {number:"03",label:"Challenge",title:"Consistency without pretending certainty.",text:"The hardest part was sourcing comparable information. Population estimates move, borders can be politically sensitive, leaders change and rankings use different dates. I had to decide what counted, keep the source and year visible, and leave room for context instead of presenting every figure as permanent truth."},
  {number:"04",label:"Governance",title:"A current office is a dated claim.",text:"Leader records are checked as an edition, not treated as timeless facts. Policy and criticism entries carry a source beside the sentence, election timing includes its legal or official basis, and regional directories are published only after the whole country list has been reviewed together."},
];

export default function MethodPage(){return <main><SiteHeader active="method"/>
  <section className="method-hero"><p>About the project · Method & making</p><div><h1>A living atlas,<br/><em>built with care.</em></h1><div><span>Why I made it</span><blockquote>“I wanted to build something that makes the world feel explorable—not another Wikipedia clone you open, skim and forget.”</blockquote><p>— Favour Imegu, creator of TerraScope</p></div></div></section>
  <section className="build-story"><header><span>Behind TerraScope</span><h2>Built / Learned / Challenge</h2></header><div>{chapters.map((chapter)=><article key={chapter.label}><span>{chapter.number}</span><small>{chapter.label}</small><h3>{chapter.title}</h3><p>{chapter.text}</p></article>)}</div></section>
  <section className="method-principles"><p>How the atlas stays honest</p><div><article><b>Source beside the claim</b><span>Important rankings keep the publisher, date and definition visible.</span></article><article><b>Context before judgement</b><span>A ranking is a lens—not a verdict on a country or its people.</span></article><article><b>Structured, then human</b><span>Data provides the backbone; clear editorial writing makes it worth exploring.</span></article></div></section>
  <section className="governance-method"><header><p>Government data protocol</p><h2>Current, critical<br/><em>and traceable.</em></h2><span>Government edition checked {governmentAsOfLabel}</span></header><div><article><span>01</span><div><h3>Current leader</h3><p>The executive office-holder, start date, term record and next scheduled national election are stored separately from general country facts so they can be refreshed without changing the geographic record.</p></div></article><article><span>02</span><div><h3>Editorial record</h3><p>Accomplishments and shortcomings are concise, attributed summaries. Each sentence links to the public body, reporting organisation or research institution used for that claim.</p></div></article><article><span>03</span><div><h3>Regional rollout</h3><p>Nigeria is the first complete template: 36 state governors plus the FCT minister. Other countries show a deliberate unavailable state until their full regional directory is ready.</p></div></article></div><footer><div><small>Core official references</small><a href="https://statehouse.gov.ng/" target="_blank" rel="noreferrer">Nigeria State House ↗</a><a href="https://www.whitehouse.gov/administration/" target="_blank" rel="noreferrer">The White House ↗</a><a href="https://www.pmindia.gov.in/en/pms-profile/" target="_blank" rel="noreferrer">Prime Minister of India ↗</a></div><div><small>Comparative record</small><a href="https://data.worldbank.org/" target="_blank" rel="noreferrer">World Bank Data ↗</a><a href="https://www.idea.int/data-tools/data/electoral-system-design-database" target="_blank" rel="noreferrer">International IDEA ↗</a><a href="https://www.un.org/en/about-us/member-states" target="_blank" rel="noreferrer">United Nations member states ↗</a></div><p>Source links for every leader-specific claim remain on the relevant country profile. A citation here describes the method; it does not replace the citation beside the claim.</p></footer></section>
  <SiteFooter/></main>}
