// Generated by scripts/refresh-indicators.mjs. Latest available World Bank observations; years differ by country and metric.
export type IndicatorRecord={value:number;year:number};
export type CountryIndicators={gdp?:IndicatorRecord;perCapita?:IndicatorRecord;lifeExpectancy?:IndicatorRecord;internet?:IndicatorRecord};
export const indicatorDataset={
  "refreshedAt": "2026-09-30",
  "sources": {
    "gdp": {
      "indicator": "NY.GDP.MKTP.CD",
      "lastUpdated": "2026-07-13",
      "url": "https://api.worldbank.org/v2/country/all/indicator/NY.GDP.MKTP.CD?format=json&mrnev=1&per_page=400"
    },
    "perCapita": {
      "indicator": "NY.GDP.PCAP.CD",
      "lastUpdated": "2026-07-13",
      "url": "https://api.worldbank.org/v2/country/all/indicator/NY.GDP.PCAP.CD?format=json&mrnev=1&per_page=400"
    },
    "lifeExpectancy": {
      "indicator": "SP.DYN.LE00.IN",
      "lastUpdated": "2026-07-13",
      "url": "https://api.worldbank.org/v2/country/all/indicator/SP.DYN.LE00.IN?format=json&mrnev=1&per_page=400"
    },
    "internet": {
      "indicator": "IT.NET.USER.ZS",
      "lastUpdated": "2026-07-13",
      "url": "https://api.worldbank.org/v2/country/all/indicator/IT.NET.USER.ZS?format=json&mrnev=1&per_page=400"
    }
  }
} as const;
export const indicatorsByCode:Record<string,CountryIndicators>={
  "AD": {
    "gdp": {
      "value": 4500982731.80784,
      "year": 2025
    },
    "perCapita": {
      "value": 54291.5026031052,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 84.188,
      "year": 2024
    },
    "internet": {
      "value": 94.39759827,
      "year": 2024
    }
  },
  "AE": {
    "gdp": {
      "value": 552324919095.872,
      "year": 2024
    },
    "perCapita": {
      "value": 50273.5126243239,
      "year": 2024
    },
    "lifeExpectancy": {
      "value": 83.069,
      "year": 2024
    },
    "internet": {
      "value": 100,
      "year": 2024
    }
  },
  "AF": {
    "gdp": {
      "value": 17778508875.7396,
      "year": 2024
    },
    "perCapita": {
      "value": 416.871146273728,
      "year": 2024
    },
    "lifeExpectancy": {
      "value": 66.289,
      "year": 2024
    },
    "internet": {
      "value": 16.09499931,
      "year": 2024
    }
  },
  "AG": {
    "gdp": {
      "value": 2338196296.2963,
      "year": 2025
    },
    "perCapita": {
      "value": 24819.2454680158,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 77.766,
      "year": 2024
    },
    "internet": {
      "value": 72.73040009,
      "year": 2024
    }
  },
  "AL": {
    "gdp": {
      "value": 30540188271.3421,
      "year": 2025
    },
    "perCapita": {
      "value": 12998.147869552,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 79.776,
      "year": 2024
    },
    "internet": {
      "value": 85.86389923,
      "year": 2024
    }
  },
  "AM": {
    "gdp": {
      "value": 29243452882.3545,
      "year": 2025
    },
    "perCapita": {
      "value": 9474.01849300368,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 78.319512195122,
      "year": 2024
    },
    "internet": {
      "value": 81.33930206,
      "year": 2024
    }
  },
  "AO": {
    "gdp": {
      "value": 122174889423.635,
      "year": 2025
    },
    "perCapita": {
      "value": 3129.47662331063,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 64.805,
      "year": 2024
    },
    "internet": {
      "value": 40.70479965,
      "year": 2024
    }
  },
  "AR": {
    "gdp": {
      "value": 683097891618.597,
      "year": 2025
    },
    "perCapita": {
      "value": 14898.0885943842,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 77.543,
      "year": 2024
    },
    "internet": {
      "value": 89.66715228,
      "year": 2024
    }
  },
  "AT": {
    "gdp": {
      "value": 579470021095.418,
      "year": 2025
    },
    "perCapita": {
      "value": 62930.0351324599,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 81.9951219512195,
      "year": 2024
    },
    "internet": {
      "value": 91.92573373,
      "year": 2025
    }
  },
  "AU": {
    "gdp": {
      "value": 1798518933689.21,
      "year": 2025
    },
    "perCapita": {
      "value": 65129.7227990563,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 83.0512195121951,
      "year": 2024
    },
    "internet": {
      "value": 96.13140106,
      "year": 2024
    }
  },
  "AZ": {
    "gdp": {
      "value": 75937647058.8235,
      "year": 2025
    },
    "perCapita": {
      "value": 7410.72281660142,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 74.576,
      "year": 2024
    },
    "internet": {
      "value": 90.80000181,
      "year": 2025
    }
  },
  "BA": {
    "gdp": {
      "value": 32599982936.3931,
      "year": 2025
    },
    "perCapita": {
      "value": 10381.8460703874,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 78.044,
      "year": 2024
    },
    "internet": {
      "value": 86.10091103,
      "year": 2024
    }
  },
  "BB": {
    "gdp": {
      "value": 8016550000,
      "year": 2025
    },
    "perCapita": {
      "value": 28364.8181499736,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 76.332,
      "year": 2024
    },
    "internet": {
      "value": 70.36470032,
      "year": 2024
    }
  },
  "BD": {
    "gdp": {
      "value": 456319229255.578,
      "year": 2025
    },
    "perCapita": {
      "value": 2597.34352335275,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 74.93,
      "year": 2024
    },
    "internet": {
      "value": 53.42171316,
      "year": 2024
    }
  },
  "BE": {
    "gdp": {
      "value": 725466462859.646,
      "year": 2025
    },
    "perCapita": {
      "value": 60750.2735864647,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 82.3,
      "year": 2024
    },
    "internet": {
      "value": 95.77579144,
      "year": 2024
    }
  },
  "BF": {
    "gdp": {
      "value": 27627297461.3181,
      "year": 2025
    },
    "perCapita": {
      "value": 1147.57131635601,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 61.292,
      "year": 2024
    },
    "internet": {
      "value": 28.25270081,
      "year": 2024
    }
  },
  "BG": {
    "gdp": {
      "value": 130777235529.606,
      "year": 2025
    },
    "perCapita": {
      "value": 20328.1667065538,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 75.7609756097561,
      "year": 2024
    },
    "internet": {
      "value": 82.438955,
      "year": 2024
    }
  },
  "BH": {
    "gdp": {
      "value": 48965725531.9149,
      "year": 2025
    },
    "perCapita": {
      "value": 30596.5794898885,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 81.423,
      "year": 2024
    },
    "internet": {
      "value": 100,
      "year": 2024
    }
  },
  "BI": {
    "gdp": {
      "value": 3364713864.08488,
      "year": 2025
    },
    "perCapita": {
      "value": 233.823013385395,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 63.818,
      "year": 2024
    },
    "internet": {
      "value": 8.595999718,
      "year": 2024
    }
  },
  "BJ": {
    "gdp": {
      "value": 24566420903.5337,
      "year": 2025
    },
    "perCapita": {
      "value": 1658.27312662991,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 60.961,
      "year": 2024
    },
    "internet": {
      "value": 33.98379898,
      "year": 2024
    }
  },
  "BN": {
    "gdp": {
      "value": 15031980994.1121,
      "year": 2025
    },
    "perCapita": {
      "value": 32234.6428368582,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 75.501,
      "year": 2024
    },
    "internet": {
      "value": 96.29828801,
      "year": 2024
    }
  },
  "BO": {
    "gdp": {
      "value": 64768947525.3256,
      "year": 2025
    },
    "perCapita": {
      "value": 5147.81081955367,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 68.739,
      "year": 2024
    },
    "internet": {
      "value": 79.70469666,
      "year": 2024
    }
  },
  "BR": {
    "gdp": {
      "value": 2279920092492.13,
      "year": 2025
    },
    "perCapita": {
      "value": 10713.2856869511,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 76.023,
      "year": 2024
    },
    "internet": {
      "value": 84.46347227,
      "year": 2024
    }
  },
  "BS": {
    "gdp": {
      "value": 15832800000,
      "year": 2024
    },
    "perCapita": {
      "value": 39455.4466548546,
      "year": 2024
    },
    "lifeExpectancy": {
      "value": 74.71,
      "year": 2024
    },
    "internet": {
      "value": 92.47270203,
      "year": 2024
    }
  },
  "BT": {
    "gdp": {
      "value": 3579320145.13077,
      "year": 2025
    },
    "perCapita": {
      "value": 4492.78400306618,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 73.262,
      "year": 2024
    },
    "internet": {
      "value": 91.27739716,
      "year": 2024
    }
  },
  "BW": {
    "gdp": {
      "value": 19928479839.4476,
      "year": 2025
    },
    "perCapita": {
      "value": 7778.1151090571,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 69.293,
      "year": 2024
    },
    "internet": {
      "value": 57.45950036,
      "year": 2024
    }
  },
  "BY": {
    "gdp": {
      "value": 93397215864.198,
      "year": 2025
    },
    "perCapita": {
      "value": 10279.2547190723,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 74.3653414634147,
      "year": 2024
    },
    "internet": {
      "value": 94.26182128,
      "year": 2024
    }
  },
  "BZ": {
    "gdp": {
      "value": 3326500000,
      "year": 2025
    },
    "perCapita": {
      "value": 7865.47937690933,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 73.739,
      "year": 2024
    },
    "internet": {
      "value": 80.00582262,
      "year": 2024
    }
  },
  "CA": {
    "gdp": {
      "value": 2319899772425.92,
      "year": 2025
    },
    "perCapita": {
      "value": 55697.6639660837,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 82.1080487804878,
      "year": 2024
    },
    "internet": {
      "value": 94.353302,
      "year": 2024
    }
  },
  "CD": {
    "gdp": {
      "value": 91030531316.9936,
      "year": 2025
    },
    "perCapita": {
      "value": 806.776000708534,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 62.074,
      "year": 2024
    },
    "internet": {
      "value": 19.67350006,
      "year": 2024
    }
  },
  "CF": {
    "gdp": {
      "value": 3066109226.40165,
      "year": 2025
    },
    "perCapita": {
      "value": 556.131398031455,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 57.671,
      "year": 2024
    },
    "internet": {
      "value": 13.78250027,
      "year": 2024
    }
  },
  "CG": {
    "gdp": {
      "value": 16306633778.765,
      "year": 2025
    },
    "perCapita": {
      "value": 2514.73393584747,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 66.001,
      "year": 2024
    },
    "internet": {
      "value": 47.25159836,
      "year": 2024
    }
  },
  "CH": {
    "gdp": {
      "value": 1043529899250.92,
      "year": 2025
    },
    "perCapita": {
      "value": 114769.012314293,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 84.4073170731707,
      "year": 2024
    },
    "internet": {
      "value": 97.32103855,
      "year": 2025
    }
  },
  "CI": {
    "gdp": {
      "value": 99773555666.1988,
      "year": 2025
    },
    "perCapita": {
      "value": 3050.10202257321,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 62.11,
      "year": 2024
    },
    "internet": {
      "value": 41.43219902,
      "year": 2024
    }
  },
  "CL": {
    "gdp": {
      "value": 357371159574.862,
      "year": 2025
    },
    "perCapita": {
      "value": 17994.5911957485,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 81.359,
      "year": 2024
    },
    "internet": {
      "value": 95.590243,
      "year": 2024
    }
  },
  "CM": {
    "gdp": {
      "value": 58933453923.761,
      "year": 2025
    },
    "perCapita": {
      "value": 1972.3815800786,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 63.968,
      "year": 2024
    },
    "internet": {
      "value": 46.25880051,
      "year": 2024
    }
  },
  "CN": {
    "gdp": {
      "value": 19498039388042.6,
      "year": 2025
    },
    "perCapita": {
      "value": 13861.970224368,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 78.017,
      "year": 2024
    },
    "internet": {
      "value": 91.6,
      "year": 2025
    }
  },
  "CO": {
    "gdp": {
      "value": 457410034202.523,
      "year": 2025
    },
    "perCapita": {
      "value": 8561.62091854449,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 77.913,
      "year": 2024
    },
    "internet": {
      "value": 79.34543299,
      "year": 2024
    }
  },
  "CR": {
    "gdp": {
      "value": 102904921157.478,
      "year": 2025
    },
    "perCapita": {
      "value": 19970.0989059622,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 80.996,
      "year": 2024
    },
    "internet": {
      "value": 87.17019653,
      "year": 2024
    }
  },
  "CU": {
    "gdp": {
      "value": 107352000000,
      "year": 2020
    },
    "perCapita": {
      "value": 9605.27914559614,
      "year": 2020
    },
    "lifeExpectancy": {
      "value": 78.264,
      "year": 2024
    },
    "internet": {
      "value": 70.47699738,
      "year": 2024
    }
  },
  "CV": {
    "gdp": {
      "value": 3056630435.32463,
      "year": 2025
    },
    "perCapita": {
      "value": 5796.47207860911,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 76.224,
      "year": 2024
    },
    "internet": {
      "value": 74.73519897,
      "year": 2024
    }
  },
  "CY": {
    "gdp": {
      "value": 41225787247.3309,
      "year": 2025
    },
    "perCapita": {
      "value": 41783.08984375,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 81.821,
      "year": 2024
    },
    "internet": {
      "value": 89.60099246,
      "year": 2024
    }
  },
  "CZ": {
    "gdp": {
      "value": 391026962800.475,
      "year": 2025
    },
    "perCapita": {
      "value": 35917.2724081665,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 79.9780487804878,
      "year": 2024
    },
    "internet": {
      "value": 87.68776014,
      "year": 2024
    }
  },
  "DE": {
    "gdp": {
      "value": 5050922925047.05,
      "year": 2025
    },
    "perCapita": {
      "value": 60496.4350820414,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 80.7926829268293,
      "year": 2024
    },
    "internet": {
      "value": 93.49999579,
      "year": 2024
    }
  },
  "DJ": {
    "gdp": {
      "value": 4624533092.31886,
      "year": 2025
    },
    "perCapita": {
      "value": 3905.604954681,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 66.202,
      "year": 2024
    },
    "internet": {
      "value": 65.29889679,
      "year": 2024
    }
  },
  "DK": {
    "gdp": {
      "value": 462526660468.393,
      "year": 2025
    },
    "perCapita": {
      "value": 76970.1535217919,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 82.2536585365854,
      "year": 2024
    },
    "internet": {
      "value": 99.76915157,
      "year": 2024
    }
  },
  "DM": {
    "gdp": {
      "value": 723859259.259259,
      "year": 2025
    },
    "perCapita": {
      "value": 10989.0431185083,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 71.294,
      "year": 2024
    },
    "internet": {
      "value": 82.04689789,
      "year": 2024
    }
  },
  "DO": {
    "gdp": {
      "value": 127407463759.043,
      "year": 2025
    },
    "perCapita": {
      "value": 11059.2081531834,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 73.868,
      "year": 2024
    },
    "internet": {
      "value": 91.0022446,
      "year": 2024
    }
  },
  "DZ": {
    "gdp": {
      "value": 287031225987.736,
      "year": 2025
    },
    "perCapita": {
      "value": 6051.00322704182,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 76.475,
      "year": 2024
    },
    "internet": {
      "value": 77.4178009,
      "year": 2024
    }
  },
  "EC": {
    "gdp": {
      "value": 130320560400,
      "year": 2025
    },
    "perCapita": {
      "value": 7125.27618527738,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 77.579,
      "year": 2024
    },
    "internet": {
      "value": 77.17273115,
      "year": 2024
    }
  },
  "EE": {
    "gdp": {
      "value": 47030833798.5866,
      "year": 2025
    },
    "perCapita": {
      "value": 34417.6320815138,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 79.2951219512195,
      "year": 2024
    },
    "internet": {
      "value": 92.23796204,
      "year": 2024
    }
  },
  "EG": {
    "gdp": {
      "value": 365254630179.737,
      "year": 2025
    },
    "perCapita": {
      "value": 3085.80712036204,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 71.806,
      "year": 2024
    },
    "internet": {
      "value": 74.64839935,
      "year": 2024
    }
  },
  "ER": {
    "gdp": {
      "value": 2065001626.01626,
      "year": 2011
    },
    "perCapita": {
      "value": 688.68165957684,
      "year": 2011
    },
    "lifeExpectancy": {
      "value": 68.893,
      "year": 2024
    },
    "internet": {
      "value": 14.34939957,
      "year": 2020
    }
  },
  "ES": {
    "gdp": {
      "value": 1906453309985.88,
      "year": 2025
    },
    "perCapita": {
      "value": 38627.2472148623,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 83.8878048780488,
      "year": 2024
    },
    "internet": {
      "value": 95.7574516,
      "year": 2024
    }
  },
  "ET": {
    "gdp": {
      "value": 126358758448.356,
      "year": 2025
    },
    "perCapita": {
      "value": 932.729352775179,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 67.603,
      "year": 2024
    },
    "internet": {
      "value": 21.94129944,
      "year": 2024
    }
  },
  "FI": {
    "gdp": {
      "value": 317039368819.607,
      "year": 2025
    },
    "perCapita": {
      "value": 56148.580949046,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 82.3365853658537,
      "year": 2024
    },
    "internet": {
      "value": 93.72405196,
      "year": 2024
    }
  },
  "FJ": {
    "gdp": {
      "value": 6198013062.06553,
      "year": 2025
    },
    "perCapita": {
      "value": 6642.00449450523,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 67.463,
      "year": 2024
    },
    "internet": {
      "value": 74.7052002,
      "year": 2024
    }
  },
  "FM": {
    "gdp": {
      "value": 501797600,
      "year": 2025
    },
    "perCapita": {
      "value": 4414.00737137479,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 67.357,
      "year": 2024
    },
    "internet": {
      "value": 39.52360153,
      "year": 2024
    }
  },
  "FR": {
    "gdp": {
      "value": 3366315927447.33,
      "year": 2025
    },
    "perCapita": {
      "value": 48985.7307807924,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 82.9804878048781,
      "year": 2024
    },
    "internet": {
      "value": 88.65381638,
      "year": 2024
    }
  },
  "GA": {
    "gdp": {
      "value": 21427119323.2764,
      "year": 2025
    },
    "perCapita": {
      "value": 8263.03321595,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 68.511,
      "year": 2024
    },
    "internet": {
      "value": 68.72090149,
      "year": 2024
    }
  },
  "GB": {
    "gdp": {
      "value": 4002587541846.01,
      "year": 2025
    },
    "perCapita": {
      "value": 57601.9621201954,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 81.3868536585366,
      "year": 2024
    },
    "internet": {
      "value": 95.4720993,
      "year": 2024
    }
  },
  "GD": {
    "gdp": {
      "value": 1420173228.56948,
      "year": 2025
    },
    "perCapita": {
      "value": 12106.8790105068,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 75.367,
      "year": 2024
    },
    "internet": {
      "value": 70.16159821,
      "year": 2024
    }
  },
  "GE": {
    "gdp": {
      "value": 38143612855.1367,
      "year": 2025
    },
    "perCapita": {
      "value": 9691.53472415196,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 74.657,
      "year": 2024
    },
    "internet": {
      "value": 83.79855689,
      "year": 2024
    }
  },
  "GH": {
    "gdp": {
      "value": 114209905278.717,
      "year": 2025
    },
    "perCapita": {
      "value": 3257.1588903576,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 65.695,
      "year": 2024
    },
    "internet": {
      "value": 72.17569733,
      "year": 2024
    }
  },
  "GM": {
    "gdp": {
      "value": 2593673987.53306,
      "year": 2025
    },
    "perCapita": {
      "value": 919.060423427951,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 66.057,
      "year": 2024
    },
    "internet": {
      "value": 49.49430084,
      "year": 2024
    }
  },
  "GN": {
    "gdp": {
      "value": 28346024753.2924,
      "year": 2025
    },
    "perCapita": {
      "value": 1877.2541220972,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 60.904,
      "year": 2024
    },
    "internet": {
      "value": 33.30469894,
      "year": 2024
    }
  },
  "GQ": {
    "gdp": {
      "value": 12823210425.9217,
      "year": 2025
    },
    "perCapita": {
      "value": 6615.25245207167,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 63.906,
      "year": 2024
    },
    "internet": {
      "value": 63.29930115,
      "year": 2024
    }
  },
  "GR": {
    "gdp": {
      "value": 280635521324.441,
      "year": 2025
    },
    "perCapita": {
      "value": 26948.0070432791,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 81.8390243902439,
      "year": 2024
    },
    "internet": {
      "value": 86.26968886,
      "year": 2024
    }
  },
  "GT": {
    "gdp": {
      "value": 123306008821.471,
      "year": 2025
    },
    "perCapita": {
      "value": 6598.18032988711,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 72.746,
      "year": 2024
    },
    "internet": {
      "value": 60.22140121,
      "year": 2024
    }
  },
  "GW": {
    "gdp": {
      "value": 2527930272.92988,
      "year": 2025
    },
    "perCapita": {
      "value": 1123.76679992349,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 64.254,
      "year": 2024
    },
    "internet": {
      "value": 29.77739906,
      "year": 2024
    }
  },
  "GY": {
    "gdp": {
      "value": 27097477218.2254,
      "year": 2025
    },
    "perCapita": {
      "value": 32413.7930757518,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 70.319,
      "year": 2024
    },
    "internet": {
      "value": 83.00080109,
      "year": 2024
    }
  },
  "HN": {
    "gdp": {
      "value": 39601409103.3005,
      "year": 2025
    },
    "perCapita": {
      "value": 3598.21450440452,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 73.044,
      "year": 2024
    },
    "internet": {
      "value": 58.62269974,
      "year": 2024
    }
  },
  "HR": {
    "gdp": {
      "value": 105060182186.274,
      "year": 2025
    },
    "perCapita": {
      "value": 27103.9116109268,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 78.9292682926829,
      "year": 2024
    },
    "internet": {
      "value": 83.63240029,
      "year": 2024
    }
  },
  "HT": {
    "gdp": {
      "value": 32077278409.2339,
      "year": 2025
    },
    "perCapita": {
      "value": 2694.18969101404,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 65.119,
      "year": 2024
    },
    "internet": {
      "value": 47.8614006,
      "year": 2024
    }
  },
  "HU": {
    "gdp": {
      "value": 246490213513.054,
      "year": 2025
    },
    "perCapita": {
      "value": 25907.4743259406,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 76.7243902439025,
      "year": 2024
    },
    "internet": {
      "value": 93.77898628,
      "year": 2024
    }
  },
  "ID": {
    "gdp": {
      "value": 1445642584163.81,
      "year": 2025
    },
    "perCapita": {
      "value": 5059.62596411213,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 71.288,
      "year": 2024
    },
    "internet": {
      "value": 72.78075544,
      "year": 2024
    }
  },
  "IE": {
    "gdp": {
      "value": 721701359046.313,
      "year": 2025
    },
    "perCapita": {
      "value": 131592.462547877,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 83.009756097561,
      "year": 2024
    },
    "internet": {
      "value": 97.18769836,
      "year": 2024
    }
  },
  "IL": {
    "gdp": {
      "value": 610777842873.595,
      "year": 2025
    },
    "perCapita": {
      "value": 60336.8477964194,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 83.1975609756098,
      "year": 2024
    },
    "internet": {
      "value": 88.18242225,
      "year": 2024
    }
  },
  "IN": {
    "gdp": {
      "value": 3956067115771.63,
      "year": 2025
    },
    "perCapita": {
      "value": 2702.47987141553,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 72.235,
      "year": 2024
    },
    "internet": {
      "value": 70,
      "year": 2025
    }
  },
  "IQ": {
    "gdp": {
      "value": 254367293538.462,
      "year": 2025
    },
    "perCapita": {
      "value": 5409.67899716967,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 72.424,
      "year": 2024
    },
    "internet": {
      "value": 81.47450256,
      "year": 2024
    }
  },
  "IR": {
    "gdp": {
      "value": 362682115433.364,
      "year": 2025
    },
    "perCapita": {
      "value": 3924.38017821898,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 77.854,
      "year": 2024
    },
    "internet": {
      "value": 85.3404007,
      "year": 2024
    }
  },
  "IS": {
    "gdp": {
      "value": 38582528789.0033,
      "year": 2025
    },
    "perCapita": {
      "value": 98323.4849517418,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 82.809756097561,
      "year": 2024
    },
    "internet": {
      "value": 98.209198,
      "year": 2024
    }
  },
  "IT": {
    "gdp": {
      "value": 2551556954100.35,
      "year": 2025
    },
    "perCapita": {
      "value": 43308.6403060733,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 83.9512195121951,
      "year": 2024
    },
    "internet": {
      "value": 89.2207202,
      "year": 2024
    }
  },
  "JM": {
    "gdp": {
      "value": 22704903217.5631,
      "year": 2025
    },
    "perCapita": {
      "value": 8002.92104076242,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 71.606,
      "year": 2024
    },
    "internet": {
      "value": 90.10870361,
      "year": 2024
    }
  },
  "JO": {
    "gdp": {
      "value": 61610052535.2113,
      "year": 2025
    },
    "perCapita": {
      "value": 5347.77731384797,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 77.981,
      "year": 2024
    },
    "internet": {
      "value": 95.62244985,
      "year": 2024
    }
  },
  "JP": {
    "gdp": {
      "value": 4435162999976.94,
      "year": 2025
    },
    "perCapita": {
      "value": 35951.0449549304,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 84.0363414634146,
      "year": 2024
    },
    "internet": {
      "value": 85.54153081,
      "year": 2024
    }
  },
  "KE": {
    "gdp": {
      "value": 135941278878.815,
      "year": 2025
    },
    "perCapita": {
      "value": 2362.86091198611,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 63.834,
      "year": 2024
    },
    "internet": {
      "value": 34.97622513,
      "year": 2024
    }
  },
  "KG": {
    "gdp": {
      "value": 22623752095.4613,
      "year": 2025
    },
    "perCapita": {
      "value": 3080.96893823359,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 72.4,
      "year": 2024
    },
    "internet": {
      "value": 92.0286026,
      "year": 2024
    }
  },
  "KH": {
    "gdp": {
      "value": 51267065842.9641,
      "year": 2025
    },
    "perCapita": {
      "value": 2872.42926639909,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 70.817,
      "year": 2024
    },
    "internet": {
      "value": 68.47530365,
      "year": 2024
    }
  },
  "KI": {
    "gdp": {
      "value": 349227254.158833,
      "year": 2025
    },
    "perCapita": {
      "value": 2558.66636011102,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 66.6,
      "year": 2024
    },
    "internet": {
      "value": 89.44029999,
      "year": 2024
    }
  },
  "KM": {
    "gdp": {
      "value": 1814920856.27026,
      "year": 2025
    },
    "perCapita": {
      "value": 2055.75921566281,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 67.023,
      "year": 2024
    },
    "internet": {
      "value": 32.51750183,
      "year": 2024
    }
  },
  "KN": {
    "gdp": {
      "value": 1183514814.81481,
      "year": 2025
    },
    "perCapita": {
      "value": 25223.0257622185,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 72.281,
      "year": 2024
    },
    "internet": {
      "value": 76.88400269,
      "year": 2024
    }
  },
  "KP": {
    "lifeExpectancy": {
      "value": 73.743,
      "year": 2024
    },
    "internet": {
      "value": 0,
      "year": 2004
    }
  },
  "KR": {
    "gdp": {
      "value": 1872374961553.15,
      "year": 2025
    },
    "perCapita": {
      "value": 36226.9663637512,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 83.6292682926829,
      "year": 2024
    },
    "internet": {
      "value": 97.89563777,
      "year": 2024
    }
  },
  "KW": {
    "gdp": {
      "value": 157209026926.418,
      "year": 2025
    },
    "perCapita": {
      "value": 32312.3119953634,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 84.580487804878,
      "year": 2024
    },
    "internet": {
      "value": 100,
      "year": 2025
    }
  },
  "KZ": {
    "gdp": {
      "value": 306239209650.024,
      "year": 2025
    },
    "perCapita": {
      "value": 14692.1331757237,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 74.531,
      "year": 2024
    },
    "internet": {
      "value": 93.39167254,
      "year": 2024
    }
  },
  "LA": {
    "gdp": {
      "value": 18302970218.5902,
      "year": 2025
    },
    "perCapita": {
      "value": 2324.76353098791,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 69.225,
      "year": 2024
    },
    "internet": {
      "value": 65.59269714,
      "year": 2024
    }
  },
  "LB": {
    "gdp": {
      "value": 25971643441.3408,
      "year": 2024
    },
    "perCapita": {
      "value": 4473.27134441128,
      "year": 2024
    },
    "lifeExpectancy": {
      "value": 77.945,
      "year": 2024
    },
    "internet": {
      "value": 80.63400269,
      "year": 2024
    }
  },
  "LC": {
    "gdp": {
      "value": 2656444444.44444,
      "year": 2025
    },
    "perCapita": {
      "value": 14745.8184305461,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 72.846,
      "year": 2024
    },
    "internet": {
      "value": 68.20500183,
      "year": 2024
    }
  },
  "LI": {
    "gdp": {
      "value": 8905764270.4054,
      "year": 2024
    },
    "perCapita": {
      "value": 220167.225473557,
      "year": 2024
    },
    "lifeExpectancy": {
      "value": 84.2,
      "year": 2024
    },
    "internet": {
      "value": 98.2641983,
      "year": 2024
    }
  },
  "LK": {
    "gdp": {
      "value": 108825231671.196,
      "year": 2025
    },
    "perCapita": {
      "value": 5002.07904353724,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 77.672,
      "year": 2024
    },
    "internet": {
      "value": 54.59,
      "year": 2024
    }
  },
  "LR": {
    "gdp": {
      "value": 5245938900,
      "year": 2025
    },
    "perCapita": {
      "value": 915.328972645548,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 62.324,
      "year": 2024
    },
    "internet": {
      "value": 32.23360062,
      "year": 2024
    }
  },
  "LS": {
    "gdp": {
      "value": 2573572920.05159,
      "year": 2025
    },
    "perCapita": {
      "value": 1088.96276223185,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 57.798,
      "year": 2024
    },
    "internet": {
      "value": 51.79660034,
      "year": 2024
    }
  },
  "LT": {
    "gdp": {
      "value": 95210150818.3512,
      "year": 2025
    },
    "perCapita": {
      "value": 32958.6706396386,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 77.1951219512195,
      "year": 2024
    },
    "internet": {
      "value": 89.16116293,
      "year": 2024
    }
  },
  "LU": {
    "gdp": {
      "value": 101157829491.107,
      "year": 2025
    },
    "perCapita": {
      "value": 147252.179121515,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 83.1951219512195,
      "year": 2024
    },
    "internet": {
      "value": 99.12902211,
      "year": 2025
    }
  },
  "LV": {
    "gdp": {
      "value": 48618869160.3254,
      "year": 2025
    },
    "perCapita": {
      "value": 26311.9730706362,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 76.4292682926829,
      "year": 2024
    },
    "internet": {
      "value": 92.70757011,
      "year": 2024
    }
  },
  "LY": {
    "gdp": {
      "value": 48098909613.6316,
      "year": 2025
    },
    "perCapita": {
      "value": 6448.82415074121,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 71.121,
      "year": 2024
    },
    "internet": {
      "value": 81.95449829,
      "year": 2024
    }
  },
  "MA": {
    "gdp": {
      "value": 182374250612.28,
      "year": 2025
    },
    "perCapita": {
      "value": 4672.46826171875,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 75.493,
      "year": 2024
    },
    "internet": {
      "value": 91.2,
      "year": 2024
    }
  },
  "MC": {
    "gdp": {
      "value": 11125788838.2812,
      "year": 2024
    },
    "perCapita": {
      "value": 288001.574856495,
      "year": 2024
    },
    "lifeExpectancy": {
      "value": 86.497,
      "year": 2024
    },
    "internet": {
      "value": 99.04489899,
      "year": 2024
    }
  },
  "MD": {
    "gdp": {
      "value": 20351796275.2943,
      "year": 2025
    },
    "perCapita": {
      "value": 8621.71721623786,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 71.332,
      "year": 2024
    },
    "internet": {
      "value": 77.3687973,
      "year": 2024
    }
  },
  "ME": {
    "gdp": {
      "value": 9232801464.79257,
      "year": 2025
    },
    "perCapita": {
      "value": 14816.8380299947,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 77.890243902439,
      "year": 2024
    },
    "internet": {
      "value": 88.88258428,
      "year": 2024
    }
  },
  "MG": {
    "gdp": {
      "value": 19620352035.7899,
      "year": 2025
    },
    "perCapita": {
      "value": 599.265294255357,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 63.835,
      "year": 2024
    },
    "internet": {
      "value": 18.67790031,
      "year": 2024
    }
  },
  "MH": {
    "gdp": {
      "value": 308000000,
      "year": 2025
    },
    "perCapita": {
      "value": 8489.05793506422,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 67.075,
      "year": 2024
    },
    "internet": {
      "value": 65.915802,
      "year": 2024
    }
  },
  "MK": {
    "gdp": {
      "value": 19101199817.0174,
      "year": 2025
    },
    "perCapita": {
      "value": 10489.9255355525,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 76.6165853658537,
      "year": 2024
    },
    "internet": {
      "value": 93.1,
      "year": 2025
    }
  },
  "ML": {
    "gdp": {
      "value": 30069148580.7688,
      "year": 2025
    },
    "perCapita": {
      "value": 1193.27601004701,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 60.675,
      "year": 2024
    },
    "internet": {
      "value": 36.80149841,
      "year": 2024
    }
  },
  "MM": {
    "gdp": {
      "value": 81665773809.5238,
      "year": 2025
    },
    "perCapita": {
      "value": 1488.87527836542,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 67.095,
      "year": 2024
    },
    "internet": {
      "value": 45.4477005,
      "year": 2020
    }
  },
  "MN": {
    "gdp": {
      "value": 25369107325.4549,
      "year": 2025
    },
    "perCapita": {
      "value": 7108.22743246244,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 72.3980487804878,
      "year": 2024
    },
    "internet": {
      "value": 85.12349701,
      "year": 2024
    }
  },
  "MR": {
    "gdp": {
      "value": 11679910946.4371,
      "year": 2025
    },
    "perCapita": {
      "value": 2197.51046251309,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 68.713,
      "year": 2024
    },
    "internet": {
      "value": 45.77939987,
      "year": 2024
    }
  },
  "MT": {
    "gdp": {
      "value": 27771821560.9411,
      "year": 2025
    },
    "perCapita": {
      "value": 47906.9000057635,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 82.9560975609756,
      "year": 2024
    },
    "internet": {
      "value": 93.86029816,
      "year": 2024
    }
  },
  "MU": {
    "gdp": {
      "value": 16157804491.7614,
      "year": 2025
    },
    "perCapita": {
      "value": 12991.2935987166,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 73.7890243902439,
      "year": 2024
    },
    "internet": {
      "value": 73.30793533,
      "year": 2024
    }
  },
  "MV": {
    "gdp": {
      "value": 7741066860.6337,
      "year": 2025
    },
    "perCapita": {
      "value": 14614.7208116541,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 81.285,
      "year": 2024
    },
    "internet": {
      "value": 85.23999786,
      "year": 2024
    }
  },
  "MW": {
    "gdp": {
      "value": 14918276698.303,
      "year": 2025
    },
    "perCapita": {
      "value": 671.506847203876,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 67.561,
      "year": 2024
    },
    "internet": {
      "value": 18.96159935,
      "year": 2024
    }
  },
  "MX": {
    "gdp": {
      "value": 1832641364775.52,
      "year": 2025
    },
    "perCapita": {
      "value": 13889.2339628708,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 75.264,
      "year": 2024
    },
    "internet": {
      "value": 83.12233799,
      "year": 2024
    }
  },
  "MY": {
    "gdp": {
      "value": 472193128644.597,
      "year": 2025
    },
    "perCapita": {
      "value": 13124.5554178269,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 76.821,
      "year": 2024
    },
    "internet": {
      "value": 98.0206059,
      "year": 2024
    }
  },
  "MZ": {
    "gdp": {
      "value": 22337997046.1913,
      "year": 2025
    },
    "perCapita": {
      "value": 626.914419215727,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 63.797,
      "year": 2024
    },
    "internet": {
      "value": 20.52729988,
      "year": 2024
    }
  },
  "NA": {
    "gdp": {
      "value": 15080340653.5276,
      "year": 2025
    },
    "perCapita": {
      "value": 4875.92558158247,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 67.516,
      "year": 2024
    },
    "internet": {
      "value": 64.87460327,
      "year": 2024
    }
  },
  "NE": {
    "gdp": {
      "value": 21646191388.2507,
      "year": 2025
    },
    "perCapita": {
      "value": 775.353622143879,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 61.433,
      "year": 2024
    },
    "internet": {
      "value": 15.55760002,
      "year": 2024
    }
  },
  "NG": {
    "gdp": {
      "value": 290794361542.112,
      "year": 2025
    },
    "perCapita": {
      "value": 1224.25410237743,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 54.635,
      "year": 2024
    },
    "internet": {
      "value": 41.21139908,
      "year": 2024
    }
  },
  "NI": {
    "gdp": {
      "value": 22237167113.0916,
      "year": 2025
    },
    "perCapita": {
      "value": 3173.33724815085,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 75.1,
      "year": 2024
    },
    "internet": {
      "value": 61.39550018,
      "year": 2024
    }
  },
  "NL": {
    "gdp": {
      "value": 1332767651100.39,
      "year": 2025
    },
    "perCapita": {
      "value": 73683.917132794,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 81.9658536585366,
      "year": 2024
    },
    "internet": {
      "value": 97.00679779,
      "year": 2024
    }
  },
  "NO": {
    "gdp": {
      "value": 530755719438.879,
      "year": 2025
    },
    "perCapita": {
      "value": 94594.1929573987,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 83.1609756097561,
      "year": 2024
    },
    "internet": {
      "value": 99,
      "year": 2024
    }
  },
  "NP": {
    "gdp": {
      "value": 45489810283.1132,
      "year": 2025
    },
    "perCapita": {
      "value": 1535.87781246307,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 70.636,
      "year": 2024
    },
    "internet": {
      "value": 46.32189941,
      "year": 2024
    }
  },
  "NR": {
    "gdp": {
      "value": 176040043.932346,
      "year": 2025
    },
    "perCapita": {
      "value": 14639.5046929186,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 62.279,
      "year": 2024
    },
    "internet": {
      "value": 83.01170349,
      "year": 2024
    }
  },
  "NZ": {
    "gdp": {
      "value": 264057413739.965,
      "year": 2025
    },
    "perCapita": {
      "value": 49591.0405731713,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 82.009756097561,
      "year": 2024
    },
    "internet": {
      "value": 93.51930237,
      "year": 2024
    }
  },
  "OM": {
    "gdp": {
      "value": 109604780696.23,
      "year": 2025
    },
    "perCapita": {
      "value": 19947.3966227092,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 80.246,
      "year": 2024
    },
    "internet": {
      "value": 95.25174678,
      "year": 2024
    }
  },
  "PA": {
    "gdp": {
      "value": 90462600000,
      "year": 2025
    },
    "perCapita": {
      "value": 19789.7308555826,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 79.775,
      "year": 2024
    },
    "internet": {
      "value": 72.77149963,
      "year": 2024
    }
  },
  "PE": {
    "gdp": {
      "value": 334854659181.893,
      "year": 2025
    },
    "perCapita": {
      "value": 9684.41170314988,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 77.941,
      "year": 2024
    },
    "internet": {
      "value": 81.95705992,
      "year": 2024
    }
  },
  "PG": {
    "gdp": {
      "value": 32498658653.8415,
      "year": 2025
    },
    "perCapita": {
      "value": 3019.5309140573,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 66.256,
      "year": 2024
    },
    "internet": {
      "value": 18.81159973,
      "year": 2024
    }
  },
  "PH": {
    "gdp": {
      "value": 487086123720.417,
      "year": 2025
    },
    "perCapita": {
      "value": 4170.72347271451,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 69.946,
      "year": 2024
    },
    "internet": {
      "value": 67.26300914,
      "year": 2024
    }
  },
  "PK": {
    "gdp": {
      "value": 407307214476.222,
      "year": 2025
    },
    "perCapita": {
      "value": 1595.90912252837,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 67.799,
      "year": 2024
    },
    "internet": {
      "value": 57.253,
      "year": 2024
    }
  },
  "PL": {
    "gdp": {
      "value": 1035491784197.44,
      "year": 2025
    },
    "perCapita": {
      "value": 28419.5777395638,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 78.409756097561,
      "year": 2024
    },
    "internet": {
      "value": 88.58496367,
      "year": 2024
    }
  },
  "PS": {
    "gdp": {
      "value": 17167100000,
      "year": 2025
    },
    "perCapita": {
      "value": 3171.10844621579,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 69.213,
      "year": 2024
    },
    "internet": {
      "value": 86.63765334,
      "year": 2023
    }
  },
  "PT": {
    "gdp": {
      "value": 346639825141.821,
      "year": 2025
    },
    "perCapita": {
      "value": 32081.8106150292,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 82.3829268292683,
      "year": 2024
    },
    "internet": {
      "value": 88.48704454,
      "year": 2024
    }
  },
  "PW": {
    "gdp": {
      "value": 345000000,
      "year": 2025
    },
    "perCapita": {
      "value": 19532.3557719527,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 69.383,
      "year": 2024
    },
    "internet": {
      "value": 83.92549896,
      "year": 2024
    }
  },
  "PY": {
    "gdp": {
      "value": 49278227554.3339,
      "year": 2025
    },
    "perCapita": {
      "value": 7026.61906146401,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 73.982,
      "year": 2024
    },
    "internet": {
      "value": 81.57806793,
      "year": 2024
    }
  },
  "QA": {
    "gdp": {
      "value": 215559615384.615,
      "year": 2025
    },
    "perCapita": {
      "value": 72524.9066385222,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 82.522,
      "year": 2024
    },
    "internet": {
      "value": 98.08540344,
      "year": 2024
    }
  },
  "RO": {
    "gdp": {
      "value": 428677977854.826,
      "year": 2025
    },
    "perCapita": {
      "value": 22537.9532108047,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 76.4585365853659,
      "year": 2024
    },
    "internet": {
      "value": 91.29048551,
      "year": 2024
    }
  },
  "RS": {
    "gdp": {
      "value": 99953324472.9042,
      "year": 2025
    },
    "perCapita": {
      "value": 15262.0464193413,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 75.9682926829268,
      "year": 2024
    },
    "internet": {
      "value": 87.69071294,
      "year": 2024
    }
  },
  "RU": {
    "gdp": {
      "value": 2561310169358.74,
      "year": 2025
    },
    "perCapita": {
      "value": 17546.609375,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 73.4404878048781,
      "year": 2024
    },
    "internet": {
      "value": 94.36495368,
      "year": 2024
    }
  },
  "RW": {
    "gdp": {
      "value": 16372132990.2271,
      "year": 2025
    },
    "perCapita": {
      "value": 1123.73874633225,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 68.017,
      "year": 2024
    },
    "internet": {
      "value": 31.70330048,
      "year": 2024
    }
  },
  "SA": {
    "gdp": {
      "value": 1276942933333.33,
      "year": 2025
    },
    "perCapita": {
      "value": 34536.6555456551,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 78.982,
      "year": 2024
    },
    "internet": {
      "value": 100,
      "year": 2024
    }
  },
  "SB": {
    "gdp": {
      "value": 1749572442.95016,
      "year": 2025
    },
    "perCapita": {
      "value": 2086.18955928928,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 70.694,
      "year": 2024
    },
    "internet": {
      "value": 29.04070091,
      "year": 2024
    }
  },
  "SC": {
    "gdp": {
      "value": 2387022853.48583,
      "year": 2025
    },
    "perCapita": {
      "value": 19449.3836346926,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 76.2951219512195,
      "year": 2024
    },
    "internet": {
      "value": 87.81800079,
      "year": 2024
    }
  },
  "SD": {
    "gdp": {
      "value": 60162634574.4689,
      "year": 2025
    },
    "perCapita": {
      "value": 1164.53991699219,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 66.521,
      "year": 2024
    },
    "internet": {
      "value": 18.60000038,
      "year": 2017
    }
  },
  "SE": {
    "gdp": {
      "value": 668998664082.081,
      "year": 2025
    },
    "perCapita": {
      "value": 63133.2126736715,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 84.0634146341463,
      "year": 2024
    },
    "internet": {
      "value": 95.76629783,
      "year": 2025
    }
  },
  "SG": {
    "gdp": {
      "value": 603869516998.738,
      "year": 2025
    },
    "perCapita": {
      "value": 98813.9788172877,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 83.3463414634146,
      "year": 2024
    },
    "internet": {
      "value": 94.37757178,
      "year": 2024
    }
  },
  "SI": {
    "gdp": {
      "value": 79648204979.3618,
      "year": 2025
    },
    "perCapita": {
      "value": 37376.2216079138,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 82.2853658536585,
      "year": 2024
    },
    "internet": {
      "value": 90.76355487,
      "year": 2024
    }
  },
  "SK": {
    "gdp": {
      "value": 154530066506.895,
      "year": 2025
    },
    "perCapita": {
      "value": 28543.6653439813,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 78.3707317073171,
      "year": 2024
    },
    "internet": {
      "value": 89.82507032,
      "year": 2024
    }
  },
  "SL": {
    "gdp": {
      "value": 7464157904.43509,
      "year": 2025
    },
    "perCapita": {
      "value": 846.296172499617,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 61.964,
      "year": 2024
    },
    "internet": {
      "value": 25.10499954,
      "year": 2024
    }
  },
  "SM": {
    "gdp": {
      "value": 2027243193.5116,
      "year": 2023
    },
    "perCapita": {
      "value": 59871.3288101478,
      "year": 2023
    },
    "lifeExpectancy": {
      "value": 85.817,
      "year": 2024
    },
    "internet": {
      "value": 97.35220337,
      "year": 2024
    }
  },
  "SN": {
    "gdp": {
      "value": 37006536238.3731,
      "year": 2025
    },
    "perCapita": {
      "value": 1954.71174194867,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 68.924,
      "year": 2024
    },
    "internet": {
      "value": 60.11780167,
      "year": 2024
    }
  },
  "SO": {
    "gdp": {
      "value": 12995200000.2658,
      "year": 2025
    },
    "perCapita": {
      "value": 661.173877723116,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 58.967,
      "year": 2024
    },
    "internet": {
      "value": 27.94020081,
      "year": 2024
    }
  },
  "SR": {
    "gdp": {
      "value": 4523657796.86421,
      "year": 2025
    },
    "perCapita": {
      "value": 7069.87230892274,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 73.757,
      "year": 2024
    },
    "internet": {
      "value": 87.4,
      "year": 2023
    }
  },
  "SS": {
    "gdp": {
      "value": 11997800760.2242,
      "year": 2015
    },
    "perCapita": {
      "value": 1080.14718624765,
      "year": 2015
    },
    "lifeExpectancy": {
      "value": 57.738,
      "year": 2024
    },
    "internet": {
      "value": 6.671000004,
      "year": 2019
    }
  },
  "ST": {
    "gdp": {
      "value": 981293586.906408,
      "year": 2025
    },
    "perCapita": {
      "value": 4084.40062145233,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 69.905,
      "year": 2024
    },
    "internet": {
      "value": 59.11759949,
      "year": 2024
    }
  },
  "SV": {
    "gdp": {
      "value": 36708110000,
      "year": 2025
    },
    "perCapita": {
      "value": 5766.72574029107,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 72.302,
      "year": 2024
    },
    "internet": {
      "value": 66.47769928,
      "year": 2024
    }
  },
  "SY": {
    "gdp": {
      "value": 23737634644.3994,
      "year": 2022
    },
    "perCapita": {
      "value": 1056.78264718197,
      "year": 2022
    },
    "lifeExpectancy": {
      "value": 72.56,
      "year": 2024
    },
    "internet": {
      "value": 33.77000046,
      "year": 2018
    }
  },
  "SZ": {
    "gdp": {
      "value": 5160679612.81734,
      "year": 2025
    },
    "perCapita": {
      "value": 4108.25221093363,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 64.264,
      "year": 2024
    },
    "internet": {
      "value": 63.40309906,
      "year": 2024
    }
  },
  "TD": {
    "gdp": {
      "value": 21472835225.4338,
      "year": 2025
    },
    "perCapita": {
      "value": 1022.33559390754,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 55.238,
      "year": 2024
    },
    "internet": {
      "value": 12.62689972,
      "year": 2024
    }
  },
  "TG": {
    "gdp": {
      "value": 11889949067.4697,
      "year": 2025
    },
    "perCapita": {
      "value": 1383.89974929887,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 62.935,
      "year": 2024
    },
    "internet": {
      "value": 39.48320007,
      "year": 2024
    }
  },
  "TH": {
    "gdp": {
      "value": 577009981112.015,
      "year": 2025
    },
    "perCapita": {
      "value": 8056.56359761558,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 76.564,
      "year": 2024
    },
    "internet": {
      "value": 90.86718789,
      "year": 2024
    }
  },
  "TJ": {
    "gdp": {
      "value": 17660626562.4832,
      "year": 2025
    },
    "perCapita": {
      "value": 1637.2542942547,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 71.927,
      "year": 2024
    },
    "internet": {
      "value": 55.79339981,
      "year": 2024
    }
  },
  "TL": {
    "gdp": {
      "value": 1902180257.82737,
      "year": 2025
    },
    "perCapita": {
      "value": 1340.9640193437,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 67.904,
      "year": 2024
    },
    "internet": {
      "value": 35.04199982,
      "year": 2021
    }
  },
  "TM": {
    "gdp": {
      "value": 49828621355.6516,
      "year": 2025
    },
    "perCapita": {
      "value": 6540.17876401136,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 70.201,
      "year": 2024
    },
    "internet": {
      "value": 17.99029922,
      "year": 2016
    }
  },
  "TN": {
    "gdp": {
      "value": 57502836548.0878,
      "year": 2025
    },
    "perCapita": {
      "value": 4656.63818386852,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 76.711,
      "year": 2024
    },
    "internet": {
      "value": 76.5,
      "year": 2024
    }
  },
  "TO": {
    "gdp": {
      "value": 679218218.578017,
      "year": 2025
    },
    "perCapita": {
      "value": 6547.18646814228,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 73.07,
      "year": 2024
    },
    "internet": {
      "value": 67.4417038,
      "year": 2024
    }
  },
  "TR": {
    "gdp": {
      "value": 1597293229287,
      "year": 2025
    },
    "perCapita": {
      "value": 18599.4420922378,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 77.421,
      "year": 2024
    },
    "internet": {
      "value": 89.77024003,
      "year": 2025
    }
  },
  "TT": {
    "gdp": {
      "value": 25942749718.4685,
      "year": 2025
    },
    "perCapita": {
      "value": 18967.2704636681,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 73.617,
      "year": 2024
    },
    "internet": {
      "value": 82.15989685,
      "year": 2024
    }
  },
  "TV": {
    "gdp": {
      "value": 57345434.7234984,
      "year": 2025
    },
    "perCapita": {
      "value": 6041.44908591428,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 67.259,
      "year": 2024
    },
    "internet": {
      "value": 35.20000076,
      "year": 2017
    }
  },
  "TZ": {
    "gdp": {
      "value": 90143496090.4411,
      "year": 2025
    },
    "perCapita": {
      "value": 1318.81921386719,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 67.212,
      "year": 2024
    },
    "internet": {
      "value": 31.16209984,
      "year": 2024
    }
  },
  "UA": {
    "gdp": {
      "value": 214233312784.397,
      "year": 2025
    },
    "perCapita": {
      "value": 5865.884765625,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 74.692,
      "year": 2024
    },
    "internet": {
      "value": 82.47489929,
      "year": 2024
    }
  },
  "UG": {
    "gdp": {
      "value": 61985829288.1496,
      "year": 2025
    },
    "perCapita": {
      "value": 1206.30450825002,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 68.487,
      "year": 2024
    },
    "internet": {
      "value": 8.949831061,
      "year": 2024
    }
  },
  "US": {
    "gdp": {
      "value": 30769700000000,
      "year": 2025
    },
    "perCapita": {
      "value": 90026.5163005744,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 78.890243902439,
      "year": 2024
    },
    "internet": {
      "value": 94.69380188,
      "year": 2024
    }
  },
  "UY": {
    "gdp": {
      "value": 85347696277.6859,
      "year": 2025
    },
    "perCapita": {
      "value": 25215.8238152781,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 78.287,
      "year": 2024
    },
    "internet": {
      "value": 91.99109007,
      "year": 2024
    }
  },
  "UZ": {
    "gdp": {
      "value": 147038081129.405,
      "year": 2025
    },
    "perCapita": {
      "value": 3968.2720079072,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 72.528,
      "year": 2024
    },
    "internet": {
      "value": 89.50550079,
      "year": 2024
    }
  },
  "VC": {
    "gdp": {
      "value": 1255222222.22222,
      "year": 2025
    },
    "perCapita": {
      "value": 12561.769166789,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 71.382,
      "year": 2024
    },
    "internet": {
      "value": 76.19010162,
      "year": 2024
    }
  },
  "VE": {
    "gdp": {
      "value": 99661244155.6306,
      "year": 2025
    },
    "perCapita": {
      "value": 3494.8138870244,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 72.673,
      "year": 2024
    },
    "internet": {
      "value": 76.67890167,
      "year": 2024
    }
  },
  "VN": {
    "gdp": {
      "value": 514697215165.065,
      "year": 2025
    },
    "perCapita": {
      "value": 5065.99091899299,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 74.736,
      "year": 2024
    },
    "internet": {
      "value": 84.15,
      "year": 2024
    }
  },
  "VU": {
    "gdp": {
      "value": 1353658840.63993,
      "year": 2025
    },
    "perCapita": {
      "value": 4038.73520713411,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 71.654,
      "year": 2024
    },
    "internet": {
      "value": 22.35140038,
      "year": 2015
    }
  },
  "WS": {
    "gdp": {
      "value": 1287936621.64619,
      "year": 2025
    },
    "perCapita": {
      "value": 5872.78333308796,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 71.826,
      "year": 2024
    },
    "internet": {
      "value": 21.20000076,
      "year": 2014
    }
  },
  "YE": {
    "gdp": {
      "value": 21606160663.0318,
      "year": 2018
    },
    "perCapita": {
      "value": 633.887202451545,
      "year": 2018
    },
    "lifeExpectancy": {
      "value": 69.439,
      "year": 2024
    },
    "internet": {
      "value": 17.49099922,
      "year": 2019
    }
  },
  "ZA": {
    "gdp": {
      "value": 427184325997.307,
      "year": 2025
    },
    "perCapita": {
      "value": 6597.71450918774,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 66.312,
      "year": 2024
    },
    "internet": {
      "value": 78.35759735,
      "year": 2024
    }
  },
  "ZM": {
    "gdp": {
      "value": 28879806220.1264,
      "year": 2025
    },
    "perCapita": {
      "value": 1317.87771619597,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 66.528,
      "year": 2024
    },
    "internet": {
      "value": 17.10099983,
      "year": 2024
    }
  },
  "ZW": {
    "gdp": {
      "value": 51215643905.5886,
      "year": 2025
    },
    "perCapita": {
      "value": 3021.43019873632,
      "year": 2025
    },
    "lifeExpectancy": {
      "value": 63.064,
      "year": 2024
    },
    "internet": {
      "value": 41.64279938,
      "year": 2024
    }
  }
};
