export type Country = {
  slug:string; name:string; official:string; code:string; flag:string; region:string; subregion:string;
  capital:string; population:number; populationLabel:string; area:number; areaLabel:string; density:string;
  languages:string[]; currency:string; leader:string; leaderTitle:string; government:string; independence:string;
  gdp:string; lifeExpectancy:string; calling:string; internet:string; timezone:string; color:string;
  summary:string; fact:string; cities:string[]; landmarks:string[]; notable:string[];
};

export const countries: Country[] = [
  {slug:"nigeria",name:"Nigeria",official:"Federal Republic of Nigeria",code:"NG",flag:"🇳🇬",region:"Africa",subregion:"Western Africa",capital:"Abuja",population:237500000,populationLabel:"237.5 million",area:923768,areaLabel:"923,768 km²",density:"257 / km²",languages:["English","Hausa","Yoruba","Igbo"],currency:"Nigerian naira (₦)",leader:"Bola Ahmed Tinubu",leaderTitle:"President",government:"Federal presidential republic",independence:"1 October 1960",gdp:"≈ US$253B",lifeExpectancy:"54.6 years",calling:"+234",internet:"≈ 45%",timezone:"WAT (UTC+1)",color:"#17845d",summary:"Africa’s most populous country is a federation of 36 states, home to hundreds of peoples and one of the world’s most influential contemporary cultures.",fact:"Nigeria’s film industry, Nollywood, is among the world’s largest by annual output.",cities:["Lagos","Kano","Ibadan","Port Harcourt"],landmarks:["Zuma Rock","Olumo Rock","Sukur Cultural Landscape"],notable:["Omah Lay","Chimamanda Ngozi Adichie","Burna Boy","Hakeem Olajuwon","Wole Soyinka","Ngozi Okonjo-Iweala"]},
  {slug:"japan",name:"Japan",official:"Japan",code:"JP",flag:"🇯🇵",region:"Asia",subregion:"Eastern Asia",capital:"Tokyo",population:123100000,populationLabel:"123.1 million",area:377975,areaLabel:"377,975 km²",density:"326 / km²",languages:["Japanese"],currency:"Japanese yen (¥)",leader:"Sanae Takaichi",leaderTitle:"Prime Minister",government:"Unitary parliamentary monarchy",independence:"Traditional founding: 660 BCE",gdp:"≈ US$4.0T",lifeExpectancy:"84.8 years",calling:"+81",internet:"≈ 87%",timezone:"JST (UTC+9)",color:"#bd3b35",summary:"An island nation where ancient ritual and high technology sit side by side, spread across an arc of nearly 14,000 islands in the Pacific.",fact:"Japan has more than 100 active volcanoes and thousands of natural hot springs.",cities:["Tokyo","Osaka","Kyoto","Yokohama"],landmarks:["Mount Fuji","Himeji Castle","Itsukushima Shrine"],notable:["Hayao Miyazaki","Naomi Osaka","Yayoi Kusama"]},
  {slug:"brazil",name:"Brazil",official:"Federative Republic of Brazil",code:"BR",flag:"🇧🇷",region:"Americas",subregion:"South America",capital:"Brasília",population:212800000,populationLabel:"212.8 million",area:8515767,areaLabel:"8.52M km²",density:"25 / km²",languages:["Portuguese"],currency:"Brazilian real (R$)",leader:"Luiz Inácio Lula da Silva",leaderTitle:"President",government:"Federal presidential republic",independence:"7 September 1822",gdp:"≈ US$2.2T",lifeExpectancy:"75.8 years",calling:"+55",internet:"≈ 84%",timezone:"UTC−5 to UTC−2",color:"#d49b33",summary:"South America’s largest country contains most of the Amazon basin, a continental coastline and an extraordinary blend of Indigenous, African and European cultures.",fact:"Brazil borders every South American country except Chile and Ecuador.",cities:["São Paulo","Rio de Janeiro","Salvador","Manaus"],landmarks:["Amazon Rainforest","Iguaçu Falls","Christ the Redeemer"],notable:["Pelé","Anitta","Oscar Niemeyer"]},
  {slug:"france",name:"France",official:"French Republic",code:"FR",flag:"🇫🇷",region:"Europe",subregion:"Western Europe",capital:"Paris",population:66600000,populationLabel:"66.6 million",area:551695,areaLabel:"551,695 km²",density:"121 / km²",languages:["French"],currency:"Euro (€)",leader:"Emmanuel Macron",leaderTitle:"President",government:"Unitary semi-presidential republic",independence:"Republic founded 22 September 1792",gdp:"≈ US$3.2T",lifeExpectancy:"83.1 years",calling:"+33",internet:"≈ 86%",timezone:"CET (UTC+1)",color:"#42658b",summary:"A European republic whose language, philosophy, cuisine, art and political ideas have travelled far beyond its metropolitan and overseas territories.",fact:"Because of its overseas territories, France has more time zones than any other country.",cities:["Paris","Marseille","Lyon","Toulouse"],landmarks:["Eiffel Tower","Mont-Saint-Michel","Palace of Versailles"],notable:["Kylian Mbappé","Coco Chanel","Victor Hugo"]},
  {slug:"united-states",name:"United States",official:"United States of America",code:"US",flag:"🇺🇸",region:"Americas",subregion:"Northern America",capital:"Washington, D.C.",population:347300000,populationLabel:"347.3 million",area:9833520,areaLabel:"9.83M km²",density:"35 / km²",languages:["English","Spanish"],currency:"US dollar ($)",leader:"Donald J. Trump",leaderTitle:"President",government:"Federal presidential republic",independence:"4 July 1776",gdp:"≈ US$29.2T",lifeExpectancy:"78.4 years",calling:"+1",internet:"≈ 97%",timezone:"UTC−12 to UTC+12",color:"#5a6787",summary:"A federal republic of 50 states spanning much of North America, with global influence across economics, science, entertainment and politics.",fact:"Alaska is both the westernmost and easternmost US state because it crosses the 180th meridian.",cities:["New York City","Los Angeles","Chicago","Houston"],landmarks:["Grand Canyon","Yellowstone","Statue of Liberty"],notable:["Serena Williams","Beyoncé","Martin Luther King Jr."]},
  {slug:"india",name:"India",official:"Republic of India",code:"IN",flag:"🇮🇳",region:"Asia",subregion:"Southern Asia",capital:"New Delhi",population:1464000000,populationLabel:"1.46 billion",area:3287263,areaLabel:"3.29M km²",density:"445 / km²",languages:["Hindi","English","22 scheduled languages"],currency:"Indian rupee (₹)",leader:"Narendra Modi",leaderTitle:"Prime Minister",government:"Federal parliamentary republic",independence:"15 August 1947",gdp:"≈ US$4.2T",lifeExpectancy:"72.0 years",calling:"+91",internet:"≈ 55%",timezone:"IST (UTC+5:30)",color:"#d47842",summary:"A vast South Asian republic shaped by millennia of civilisation, immense linguistic variety and the world’s largest population.",fact:"India is home to the world’s largest postal network, including a floating post office in Kashmir.",cities:["Delhi","Mumbai","Bengaluru","Kolkata"],landmarks:["Taj Mahal","Jaipur","Sundarbans"],notable:["A. R. Rahman","Priyanka Chopra Jonas","Viswanathan Anand"]},
  {slug:"south-africa",name:"South Africa",official:"Republic of South Africa",code:"ZA",flag:"🇿🇦",region:"Africa",subregion:"Southern Africa",capital:"Pretoria · Cape Town · Bloemfontein",population:64700000,populationLabel:"64.7 million",area:1221037,areaLabel:"1.22M km²",density:"53 / km²",languages:["Zulu","Xhosa","Afrikaans","English + 8"],currency:"South African rand (R)",leader:"Cyril Ramaphosa",leaderTitle:"President",government:"Unitary parliamentary republic",independence:"Union: 31 May 1910",gdp:"≈ US$410B",lifeExpectancy:"66.1 years",calling:"+27",internet:"≈ 76%",timezone:"SAST (UTC+2)",color:"#56795d",summary:"A biodiverse nation at Africa’s southern tip, defined by eleven official languages, dramatic landscapes and a long struggle for democratic freedom.",fact:"South Africa is the only country with three separate capital cities.",cities:["Johannesburg","Cape Town","Durban","Pretoria"],landmarks:["Table Mountain","Kruger National Park","Robben Island"],notable:["Nelson Mandela","Trevor Noah","Miriam Makeba"]},
  {slug:"mexico",name:"Mexico",official:"United Mexican States",code:"MX",flag:"🇲🇽",region:"Americas",subregion:"Central America",capital:"Mexico City",population:131900000,populationLabel:"131.9 million",area:1964375,areaLabel:"1.96M km²",density:"67 / km²",languages:["Spanish","68 national Indigenous languages"],currency:"Mexican peso ($)",leader:"Claudia Sheinbaum",leaderTitle:"President",government:"Federal presidential republic",independence:"16 September 1810",gdp:"≈ US$1.8T",lifeExpectancy:"75.1 years",calling:"+52",internet:"≈ 81%",timezone:"UTC−8 to UTC−5",color:"#687b58",summary:"A North American federation built on deep Mesoamerican roots, celebrated for its foodways, visual arts and remarkable geographic range.",fact:"Mexico is one of the world’s megadiverse countries, with desert, rainforest, cloud forest and coral reef ecosystems.",cities:["Mexico City","Guadalajara","Monterrey","Puebla"],landmarks:["Chichén Itzá","Copper Canyon","Teotihuacan"],notable:["Frida Kahlo","Guillermo del Toro","Carlos Santana"]},
  {slug:"egypt",name:"Egypt",official:"Arab Republic of Egypt",code:"EG",flag:"🇪🇬",region:"Africa",subregion:"Northern Africa",capital:"Cairo",population:118400000,populationLabel:"118.4 million",area:1002450,areaLabel:"1.00M km²",density:"118 / km²",languages:["Arabic"],currency:"Egyptian pound (E£)",leader:"Abdel Fattah el-Sisi",leaderTitle:"President",government:"Unitary semi-presidential republic",independence:"28 February 1922",gdp:"≈ US$347B",lifeExpectancy:"71.6 years",calling:"+20",internet:"≈ 72%",timezone:"EET (UTC+2)",color:"#b48a55",summary:"A transcontinental nation anchored by the Nile, where one of humanity’s earliest urban civilisations meets the contemporary Arab world.",fact:"About 95% of Egypt’s population lives close to the Nile and its delta.",cities:["Cairo","Alexandria","Giza","Luxor"],landmarks:["Giza pyramid complex","Valley of the Kings","Abu Simbel"],notable:["Mohamed Salah","Naguib Mahfouz","Umm Kulthum"]},
  {slug:"australia",name:"Australia",official:"Commonwealth of Australia",code:"AU",flag:"🇦🇺",region:"Oceania",subregion:"Australia and New Zealand",capital:"Canberra",population:27200000,populationLabel:"27.2 million",area:7692024,areaLabel:"7.69M km²",density:"3.5 / km²",languages:["English","250+ Indigenous languages historically"],currency:"Australian dollar (A$)",leader:"Anthony Albanese",leaderTitle:"Prime Minister",government:"Federal parliamentary monarchy",independence:"Federation: 1 January 1901",gdp:"≈ US$1.8T",lifeExpectancy:"83.2 years",calling:"+61",internet:"≈ 97%",timezone:"UTC+8 to UTC+11",color:"#4c7280",summary:"The world’s smallest continent and sixth-largest country, carrying more than 65,000 years of continuous Indigenous cultures.",fact:"Australia’s dingo fence stretches for more than 5,600 kilometres across the continent.",cities:["Sydney","Melbourne","Brisbane","Perth"],landmarks:["Great Barrier Reef","Uluru","Sydney Opera House"],notable:["Cathy Freeman","Chris Hemsworth","Kylie Minogue"]},
];

export const people = [
  {name:"Omah Lay",country:"Nigeria",role:"Singer · Songwriter",years:"1997 —",initials:"OL",tone:"#17845d"},
  {name:"Chimamanda Ngozi Adichie",country:"Nigeria",role:"Writer",years:"1977 —",initials:"CA",tone:"#6d7c62"},
  {name:"Nelson Mandela",country:"South Africa",role:"Statesman",years:"1918 — 2013",initials:"NM",tone:"#3d6055"},
  {name:"Frida Kahlo",country:"Mexico",role:"Artist",years:"1907 — 1954",initials:"FK",tone:"#b35a3d"},
  {name:"Hayao Miyazaki",country:"Japan",role:"Filmmaker",years:"1941 —",initials:"HM",tone:"#536e78"},
  {name:"Pelé",country:"Brazil",role:"Footballer",years:"1940 — 2022",initials:"PE",tone:"#b28a3e"},
  {name:"Marie Curie",country:"Poland · France",role:"Physicist",years:"1867 — 1934",initials:"MC",tone:"#6a697d"},
];
