import type {CityGuide,CityGuideExtra} from "./country-content";

// Original planning notes. Heritage references are recorded below; access,
// ticket prices and transport availability are deliberately not asserted.
export const discoveryGuides:CityGuide[]=[
 {countryCode:"NG",countrySlug:"nigeria",citySlug:"abeokuta",name:"Abeokuta",country:"Nigeria",overview:"Build a slower outing around Olumo Rock, Egba heritage and local markets. Keep time for exploring on foot rather than treating the city as a single photo stop.",bestTime:"Plan for a dry day and start outdoor visits early. Check the local forecast rather than relying on a seasonal average.",attractions:["Olumo Rock tourist centre","Olumo Rock art and heritage area"],food:["Ofada rice","Amala with ewedu","Moin moin"],gettingAround:"Arrange a trusted driver for a multi-stop day. Agree waiting time and the return journey before departure.",safety:"Confirm which paths and facilities are open at Olumo Rock. Ask about steps and alternative access if mobility is a concern.",gallery:[]},
 {countryCode:"NG",countrySlug:"nigeria",citySlug:"osogbo",name:"Osogbo",country:"Nigeria",overview:"Osogbo’s sacred grove brings forest, river, sculpture and living Yoruba religious heritage together. Treat it as a place of worship as well as an outdoor cultural visit.",bestTime:"Choose a day with manageable rain and heat. Festivals can alter access, accommodation demand and the pace of a visit.",attractions:["Osun-Osogbo Sacred Grove","Osun river and shrine landscape","Sculpture and art within the sacred grove"],food:["Amala with ewedu","Gbegiri","Pounded yam with soup"],gettingAround:"Book transport between your accommodation and the grove. Walk only permitted routes with locally appropriate guidance.",safety:"Follow guidance around shrines and the river; do not assume swimming or unrestricted photography is permitted.",gallery:[]},
 {countryCode:"EG",countrySlug:"egypt",citySlug:"alexandria",name:"Alexandria",country:"Egypt",overview:"Egypt’s Mediterranean city offers a different rhythm from Cairo: waterfront orientation, ancient burial sites and coastal fortifications. Group stops geographically and leave space for a relaxed meal.",bestTime:"Spring and autumn can be useful starting points; check coastal weather and holiday crowds for your actual dates.",attractions:["Qaitbay Citadel","Kom el-Shoqafa catacombs","Eastern Harbour waterfront"],food:["Grilled fish","Ful medames","Falafel","Koshari"],gettingAround:"Choose a taxi or established ride service for longer hops and group nearby waterfront stops together. Confirm rail or road arrangements if arriving from Cairo.",safety:"Check steps, enclosed spaces and photography rules at archaeological sites. Keep a weather alternative for waterfront time.",gallery:[]},
 {countryCode:"EG",countrySlug:"egypt",citySlug:"aswan",name:"Aswan",country:"Egypt",overview:"Aswan connects Nile islands, granite quarries and Nubian heritage. Combine land visits and a carefully arranged boat trip rather than trying to fit every monument into one hot afternoon.",bestTime:"October to April is generally a more comfortable planning window for outdoor visits. Summer heat requires a much lighter pace.",attractions:["Philae temples on Agilkia Island","Unfinished Obelisk","Nubian Museum","Elephantine Island"],food:["Ful medames","Grilled fish","Koshari","Hibiscus drink"],gettingAround:"Separate road journeys from island visits. Confirm the boat’s departure point, return time, safety equipment and whether transfers are in the quote.",safety:"Bring drinking water and shade. Check official site notices and confirm which entrances, boats and exhibits are operating.",gallery:[]},
];

export const discoveryGuideExtras:Record<string,CityGuideExtra>={
 "nigeria/abeokuta":{gateway:"Compare road or rail connections from Lagos with your chosen arrival point; confirm current services.",neighbourhoods:[{name:"Olumo Rock area",note:"A useful focus for the heritage portion of your outing; check the actual distance from your accommodation."},{name:"City-centre base",note:"Choose accommodation with a reliable pick-up point and confirm late check-in arrangements."}],dayTrips:[],itinerary:[{day:"Day 01",title:"Rock and heritage",plan:"Start at Olumo Rock; check permitted routes and spend the afternoon on a relaxed meal rather than adding distant stops."},{day:"Day 02",title:"Art and local life",plan:"Confirm any art displays and guided visits ahead, then leave time for a market visit with local guidance."},{day:"Day 03",title:"Your kind of fun",plan:"Choose a workshop, cinema or pool outing only after identifying an operating venue and a quote. Keep the return journey in the budget."}],cultureTips:["Ask before photographing people, ceremonies or private compounds.","Confirm guide and admission charges before starting.","Bring suitable footwear for an outdoor heritage visit.","Keep purchases, meals and return transport separate in your budget."]},
 "nigeria/osogbo":{gateway:"Compare a confirmed road connection from your arrival city; do not assume a direct scheduled flight.",neighbourhoods:[{name:"Grove-access base",note:"Choose a convenient pick-up point for your visit and confirm the entrance you will use."},{name:"Central Osogbo",note:"Ask accommodation staff about current local transport and suitable food stops."}],dayTrips:[],itinerary:[{day:"Day 01",title:"Understand the grove",plan:"Take a permitted guided route through the sacred landscape and ask about the meanings of shrines and artworks."},{day:"Day 02",title:"Culture at a slower pace",plan:"Arrange a local art or craft visit if available; leave the afternoon open for food and rest."},{day:"Day 03",title:"A flexible outing",plan:"Choose an available creative workshop or a relaxed picnic at a permitted venue. Avoid treating sacred ground as a recreation park."}],cultureTips:["Respect religious boundaries and local requests.","Ask about photography before taking pictures of shrines or ceremonies.","Confirm festival arrangements and accommodation availability for your dates.","Do not enter the river or leave marked routes without permission."]},
 "egypt/alexandria":{gateway:"Borg El Arab airport serves the Alexandria area; confirm ground transfer or a connection from Cairo.",neighbourhoods:[{name:"Waterfront base",note:"Useful for coastal orientation; compare the location of your hotel with the specific sights you choose."},{name:"Central city",note:"A practical alternative when your priorities are food and transport connections rather than a sea view."}],dayTrips:[],itinerary:[{day:"Day 01",title:"Coastal orientation",plan:"Pair Qaitbay Citadel with nearby waterfront time, allowing for weather and a meal."},{day:"Day 02",title:"Ancient layers",plan:"Visit the catacombs with time for entry checks, steps and a shorter afternoon outing."},{day:"Day 03",title:"Make it yours",plan:"Add a confirmed cultural stop or indoor fun activity, then leave enough time for your onward connection."}],cultureTips:["Check monument ticket categories and payment methods before arrival.","Ask about access if stairs or enclosed spaces may be difficult.","Confirm photography rules at each site.","Choose a weather alternative for outdoor coastal time."]},
 "egypt/aswan":{gateway:"Aswan International Airport or a confirmed rail connection; arrange the final transfer before arrival.",neighbourhoods:[{name:"Nile-side base",note:"Check whether the property is on the mainland or an island; boat transfers can affect your daily schedule."},{name:"Mainland base",note:"A useful option for road access to the museum and quarry visits."}],dayTrips:[{name:"Abu Simbel temples",note:"This is a long extension, not a nearby city stop. Confirm an authorised transport plan, journey time and current access before including it."}],itinerary:[{day:"Day 01",title:"Stone and heritage",plan:"Start early at the Unfinished Obelisk and pair it with the Nubian Museum if current opening hours allow."},{day:"Day 02",title:"An island day",plan:"Arrange a return boat transfer to Philae and leave room for rest rather than stacking distant stops."},{day:"Day 03",title:"Choose your extension",plan:"Choose either a slower island visit or a prearranged Abu Simbel extension. Confirm transport before committing the day."}],cultureTips:["Confirm whether boat and road transfers are separate charges.","Ask permission before photographing people.","Plan outdoor time early and carry water.","Check each monument’s current ticket and opening notice."]},
};

export const discoverySources:Record<string,{label:string;url:string;checkedAt:string}>={
 "nigeria/abeokuta":{label:"Ogun State investment office · Olumo Rock",url:"https://invest.ogunstate.gov.ng/blogdetails?id=7",checkedAt:"2026-09-30"},
 "nigeria/osogbo":{label:"UNESCO · Osun-Osogbo Sacred Grove",url:"https://whc.unesco.org/en/list/1118/",checkedAt:"2026-09-30"},
 "egypt/alexandria":{label:"Egypt Ministry of Tourism and Antiquities · Alexandria",url:"https://egymonuments.gov.eg/archaeological-sites/alexandria/",checkedAt:"2026-09-30"},
 "egypt/aswan":{label:"Egypt Ministry of Tourism and Antiquities · Aswan",url:"https://egymonuments.gov.eg/archaeological-sites/aswan/",checkedAt:"2026-09-30"},
};
