export type FootballPerson = {name: string; note: string};
export type FootballProfile = {
  team: string;
  confederation: string;
  badge: string;
  worldCup: string;
  continental: string;
  achievements: string[];
  current: FootballPerson[];
  legends: FootballPerson[];
};

export const footballProfiles: Record<string, FootballProfile> = {
  NG: {team:"Super Eagles · Super Falcons",confederation:"CAF · WAFU",badge:"NG",worldCup:"Men: Round of 16 in 1994, 1998 and 2014",continental:"Men: 3× Africa Cup of Nations champions",achievements:["AFCON champions in 1980, 1994 and 2013","Olympic men’s football gold at Atlanta 1996","Super Falcons are record Women’s Africa Cup of Nations winners","Nigeria won the FIFA U-17 World Cup a record five times"],current:[{name:"Victor Osimhen",note:"Striker · African Footballer of the Year 2023"},{name:"Ademola Lookman",note:"Forward · African Footballer of the Year 2024"},{name:"Chiamaka Nnadozie",note:"Goalkeeper · Super Falcons leader"}],legends:[{name:"Jay-Jay Okocha",note:"Midfield artist and Olympic champion"},{name:"Nwankwo Kanu",note:"Olympic champion and two-time African Player of the Year"},{name:"Rashidi Yekini",note:"Nigeria men’s record-setting goal pioneer"}]},
  BR: {team:"Seleção",confederation:"CONMEBOL",badge:"BR",worldCup:"5× champions · men’s record",continental:"9× Copa América champions",achievements:["World champions in 1958, 1962, 1970, 1994 and 2002","Only men’s national team to appear at every World Cup","Olympic men’s gold in 2016 and 2020","Brazil helped define football’s global creative vocabulary"],current:[{name:"Vinícius Júnior",note:"Forward · Real Madrid"},{name:"Rodrygo",note:"Forward · Real Madrid"},{name:"Alisson Becker",note:"Goalkeeper · Liverpool"}],legends:[{name:"Pelé",note:"Three-time men’s World Cup winner"},{name:"Marta",note:"Six-time FIFA World Player of the Year"},{name:"Ronaldo Nazário",note:"Two-time Ballon d’Or winner"}]},
  FR: {team:"Les Bleus · Les Bleues",confederation:"UEFA",badge:"FR",worldCup:"2× men’s champions",continental:"2× men’s European champions",achievements:["World champions in 1998 and 2018","World Cup finalists in 2006 and 2022","European champions in 1984 and 2000","A renowned national academy network supplies elite football worldwide"],current:[{name:"Kylian Mbappé",note:"Forward · France captain"},{name:"Ousmane Dembélé",note:"Forward · Paris Saint-Germain"},{name:"William Saliba",note:"Defender · Arsenal"}],legends:[{name:"Zinedine Zidane",note:"1998 World Cup and 2000 Euro winner"},{name:"Thierry Henry",note:"Record-era forward and World Cup winner"},{name:"Michel Platini",note:"Three-time Ballon d’Or winner"}]},
  JP: {team:"Samurai Blue · Nadeshiko Japan",confederation:"AFC",badge:"JP",worldCup:"Men: four Round-of-16 appearances",continental:"Men: 4× AFC Asian Cup champions",achievements:["Nadeshiko Japan won the 2011 Women’s World Cup","Men’s Asian champions in 1992, 2000, 2004 and 2011","Co-hosted the 2002 FIFA World Cup","The J.League launched in 1993 and transformed the domestic game"],current:[{name:"Takefusa Kubo",note:"Attacking midfielder · Real Sociedad"},{name:"Kaoru Mitoma",note:"Winger · Brighton"},{name:"Yui Hasegawa",note:"Midfielder · Nadeshiko Japan"}],legends:[{name:"Hidetoshi Nakata",note:"Asian football trailblazer in Europe"},{name:"Keisuke Honda",note:"Scored at three consecutive World Cups"},{name:"Homare Sawa",note:"2011 world champion and Golden Ball winner"}]},
  US: {team:"USMNT · USWNT",confederation:"CONCACAF",badge:"US",worldCup:"Men: semi-final in 1930 · Women: 4× champions",continental:"Multiple CONCACAF titles",achievements:["USWNT won the World Cup in 1991, 1999, 2015 and 2019","Men reached the 2002 World Cup quarter-final","Co-host of the 2026 men’s World Cup","Major League Soccer began play in 1996"],current:[{name:"Christian Pulisic",note:"Forward · AC Milan"},{name:"Antonee Robinson",note:"Defender · Fulham"},{name:"Sophia Wilson",note:"Forward · USWNT"}],legends:[{name:"Mia Hamm",note:"Two-time world champion"},{name:"Landon Donovan",note:"USMNT tournament icon"},{name:"Clint Dempsey",note:"Scored at three World Cups"}]},
  IN: {team:"Blue Tigers · Blue Tigresses",confederation:"AFC · SAFF",badge:"IN",worldCup:"No senior World Cup finals appearance",continental:"AFC Asian Cup runners-up in 1964",achievements:["Asian Games men’s champions in 1951 and 1962","India qualified for the 1950 World Cup but withdrew","SAFF Championship is a major regional record","The Indian Super League began in 2014"],current:[{name:"Lallianzuala Chhangte",note:"Winger · India international"},{name:"Sandesh Jhingan",note:"Defender · India international"},{name:"Manisha Kalyan",note:"Forward · India women"}],legends:[{name:"Sunil Chhetri",note:"Long-serving captain and scoring icon"},{name:"Bhaichung Bhutia",note:"Pioneer of the modern national team"},{name:"Chuni Goswami",note:"Captain of the 1962 Asian Games champions"}]},
  ZA: {team:"Bafana Bafana · Banyana Banyana",confederation:"CAF · COSAFA",badge:"ZA",worldCup:"Men: hosted the 2010 World Cup",continental:"Men: AFCON champions in 1996",achievements:["First African nation to host a men’s FIFA World Cup","Banyana Banyana won WAFCON 2022","Men won AFCON on home soil in 1996","Orlando Pirates and Mamelodi Sundowns are continental club champions"],current:[{name:"Ronwen Williams",note:"Goalkeeper · Bafana Bafana captain"},{name:"Teboho Mokoena",note:"Midfielder · Mamelodi Sundowns"},{name:"Thembi Kgatlana",note:"Forward · Banyana Banyana"}],legends:[{name:"Benni McCarthy",note:"UEFA Champions League winner"},{name:"Lucas Radebe",note:"Bafana captain and Leeds United icon"},{name:"Doctor Khumalo",note:"1996 AFCON champion"}]},
  MX: {team:"El Tri",confederation:"CONCACAF",badge:"MX",worldCup:"Men: quarter-finals in 1970 and 1986",continental:"Record-setting CONCACAF champion",achievements:["Hosted the men’s World Cup in 1970 and 1986","Co-host of the 2026 men’s World Cup","Olympic men’s gold at London 2012","Seven consecutive men’s World Cup Round-of-16 appearances from 1994 to 2018"],current:[{name:"Santiago Giménez",note:"Striker · Mexico international"},{name:"Edson Álvarez",note:"Midfielder · Mexico captaincy group"},{name:"María Sánchez",note:"Winger · Mexico women"}],legends:[{name:"Hugo Sánchez",note:"Five-time Pichichi winner in Spain"},{name:"Rafael Márquez",note:"Captain at five World Cups"},{name:"Cuauhtémoc Blanco",note:"Creative national-team icon"}]},
  EG: {team:"The Pharaohs",confederation:"CAF · UNAF",badge:"EG",worldCup:"Men: three finals appearances",continental:"Record 7× Africa Cup of Nations champions",achievements:["AFCON champions in 1957, 1959, 1986, 1998, 2006, 2008 and 2010","Only team to win three consecutive AFCON titles","Al Ahly are Africa’s most decorated continental club","Egypt appeared at the 1934 World Cup, Africa’s first finals representative"],current:[{name:"Mohamed Salah",note:"Forward · Egypt captain"},{name:"Omar Marmoush",note:"Forward · Manchester City"},{name:"Mostafa Mohamed",note:"Striker · Egypt international"}],legends:[{name:"Mohamed Aboutrika",note:"Two-time BBC African Footballer of the Year"},{name:"Essam El Hadary",note:"Four-time AFCON-winning goalkeeper"},{name:"Hossam Hassan",note:"Three-time AFCON champion"}]},
  AU: {team:"Socceroos · Matildas",confederation:"AFC",badge:"AU",worldCup:"Men: Round of 16 in 2006 and 2022",continental:"Men: AFC Asian Cup champions in 2015",achievements:["Matildas reached the 2023 Women’s World Cup semi-final","Australia is the only nation to win two different confederations’ senior men’s titles","Hosted the 2023 Women’s World Cup with New Zealand","Socceroos won the Asian Cup on home soil in 2015"],current:[{name:"Sam Kerr",note:"Striker · Matildas captaincy group"},{name:"Mary Fowler",note:"Forward · Matildas"},{name:"Jackson Irvine",note:"Midfielder · Socceroos captain"}],legends:[{name:"Tim Cahill",note:"Scored at three World Cups"},{name:"Mark Schwarzer",note:"Long-serving Socceroos goalkeeper"},{name:"Cheryl Salisbury",note:"Matildas appearance pioneer"}]},
  AR: {team:"La Albiceleste",confederation:"CONMEBOL",badge:"AR",worldCup:"3× men’s champions",continental:"16× Copa América champions",achievements:["World champions in 1978, 1986 and 2022","Copa América champions in 2021 and 2024","Olympic men’s gold in 2004 and 2008","One of world football’s great player-producing cultures"],current:[{name:"Lionel Messi",note:"World Cup-winning captain"},{name:"Julián Álvarez",note:"Forward · Atlético Madrid"},{name:"Alexis Mac Allister",note:"Midfielder · Liverpool"}],legends:[{name:"Diego Maradona",note:"Captain of the 1986 world champions"},{name:"Alfredo Di Stéfano",note:"Transformative European club icon"},{name:"Gabriel Batistuta",note:"Three-time World Cup striker"}]},
  GB: {team:"England · Three Lions · Lionesses",confederation:"UEFA",badge:"ENG",worldCup:"Men: champions in 1966",continental:"Women: European champions in 2022",achievements:["Men’s FIFA World Cup champions in 1966","Men’s European Championship finalists in 2020 and 2024","Lionesses won UEFA Women’s Euro 2022","England is home to the world’s oldest national football association"],current:[{name:"Bukayo Saka",note:"Winger · Arsenal and England"},{name:"Jude Bellingham",note:"Midfielder · Real Madrid and England"},{name:"Lauren James",note:"Forward · Chelsea and England"}],legends:[{name:"Bobby Charlton",note:"1966 World Cup winner and Ballon d’Or recipient"},{name:"Wayne Rooney",note:"Long-serving England captain and goalscorer"},{name:"Kelly Smith",note:"Lionesses scoring pioneer"}]},
  ES: {team:"La Roja",confederation:"UEFA",badge:"ES",worldCup:"Men: champions in 2010",continental:"Men: record 4× European champions",achievements:["Euro champions in 1964, 2008, 2012 and 2024","Women won the 2023 World Cup","Only men’s team to win three consecutive major titles from 2008 to 2012","La Liga houses two of football’s most influential clubs"],current:[{name:"Lamine Yamal",note:"Winger · Barcelona"},{name:"Rodri",note:"Midfielder · Ballon d’Or 2024"},{name:"Aitana Bonmatí",note:"Midfielder · world champion"}],legends:[{name:"Andrés Iniesta",note:"2010 World Cup final match-winner"},{name:"Xavi",note:"Midfield architect of a golden era"},{name:"Iker Casillas",note:"Captain of three consecutive major titles"}]},
  DE: {team:"Nationalmannschaft",confederation:"UEFA",badge:"DE",worldCup:"Men: 4× champions · Women: 2× champions",continental:"Men: 3× European champions",achievements:["Men’s world champions in 1954, 1974, 1990 and 2014","Women’s world champions in 2003 and 2007","Hosted the men’s World Cup in 1974 and 2006","The Bundesliga is built around a national club-licensing system"],current:[{name:"Jamal Musiala",note:"Attacking midfielder · Bayern Munich"},{name:"Florian Wirtz",note:"Attacking midfielder · Liverpool"},{name:"Giulia Gwinn",note:"Defender · Germany women"}],legends:[{name:"Franz Beckenbauer",note:"World champion as player and coach"},{name:"Miroslav Klose",note:"Men’s World Cup record scorer"},{name:"Birgit Prinz",note:"Three-time FIFA World Player of the Year"}]},
  IT: {team:"Azzurri · Azzurre",confederation:"UEFA",badge:"IT",worldCup:"Men: 4× champions",continental:"Men: 2× European champions",achievements:["World champions in 1934, 1938, 1982 and 2006","European champions in 1968 and 2020","Italian clubs have won every major European trophy","A tradition renowned for tactical innovation and elite defending"],current:[{name:"Gianluigi Donnarumma",note:"Goalkeeper · national-team captaincy group"},{name:"Nicolò Barella",note:"Midfielder · Inter"},{name:"Alessandro Bastoni",note:"Defender · Inter"}],legends:[{name:"Paolo Maldini",note:"Defensive standard-bearer"},{name:"Roberto Baggio",note:"Ballon d’Or-winning playmaker"},{name:"Gianluigi Buffon",note:"2006 world champion goalkeeper"}]},
  PT: {team:"Seleção das Quinas",confederation:"UEFA",badge:"PT",worldCup:"Men: third place in 1966",continental:"Men: European champions in 2016",achievements:["UEFA Nations League champions in 2019 and 2025","Euro 2016 champions","A celebrated academy and player-development system","FC Porto and Benfica are multiple European champions"],current:[{name:"Vitinha",note:"Midfielder · Paris Saint-Germain"},{name:"Nuno Mendes",note:"Defender · Paris Saint-Germain"},{name:"Bruno Fernandes",note:"Midfielder · Manchester United"}],legends:[{name:"Cristiano Ronaldo",note:"Portugal’s record-era captain and scorer"},{name:"Eusébio",note:"1965 Ballon d’Or winner"},{name:"Luís Figo",note:"2000 Ballon d’Or winner"}]},
  MA: {team:"Atlas Lions · Atlas Lionesses",confederation:"CAF · UNAF",badge:"MA",worldCup:"Men: semi-finalists in 2022",continental:"Men: AFCON champions in 1976",achievements:["First African and Arab men’s team to reach a World Cup semi-final","Men reached the World Cup Round of 16 in 1986","Hosted the 2022 Women’s Africa Cup of Nations","Wydad and Raja Casablanca are continental club champions"],current:[{name:"Achraf Hakimi",note:"Defender · Morocco captain"},{name:"Brahim Díaz",note:"Attacking midfielder · Real Madrid"},{name:"Ghizlane Chebbak",note:"Midfielder · Atlas Lionesses"}],legends:[{name:"Mustapha Hadji",note:"African Footballer of the Year 1998"},{name:"Ahmed Faras",note:"Captain of the 1976 AFCON champions"},{name:"Noureddine Naybet",note:"Long-serving national-team defender"}]},
  GH: {team:"Black Stars · Black Queens",confederation:"CAF · WAFU",badge:"GH",worldCup:"Men: quarter-finalists in 2010",continental:"Men: 4× AFCON champions",achievements:["AFCON champions in 1963, 1965, 1978 and 1982","Reached the 2010 World Cup quarter-final","FIFA U-20 World Cup champions in 2009","Two consecutive World Cup Round-of-16 appearances in 2006 and 2010"],current:[{name:"Mohammed Kudus",note:"Attacking midfielder · Ghana international"},{name:"Thomas Partey",note:"Midfielder · Ghana international"},{name:"Abdul Fatawu",note:"Winger · Ghana international"}],legends:[{name:"Abedi Pelé",note:"Three-time African Footballer of the Year"},{name:"Asamoah Gyan",note:"Africa’s leading men’s World Cup scorer"},{name:"Samuel Kuffour",note:"UEFA Champions League-winning defender"}]},
  SN: {team:"Lions of Teranga",confederation:"CAF · WAFU",badge:"SN",worldCup:"Men: quarter-finalists in 2002",continental:"Men: AFCON champions in 2021",achievements:["AFCON 2021 champions","World Cup quarter-finalists on debut in 2002","Qualified for three men’s World Cups","A strong academy pathway supplies clubs across Europe and Africa"],current:[{name:"Nicolas Jackson",note:"Forward · Senegal international"},{name:"Pape Matar Sarr",note:"Midfielder · Tottenham"},{name:"Iliman Ndiaye",note:"Forward · Senegal international"}],legends:[{name:"Sadio Mané",note:"AFCON-winning national icon"},{name:"El Hadji Diouf",note:"Two-time African Footballer of the Year"},{name:"Henri Camara",note:"Long-serving tournament forward"}]},
  CM: {team:"Indomitable Lions",confederation:"CAF · UNIFFAC",badge:"CM",worldCup:"Men: quarter-finalists in 1990",continental:"Men: 5× AFCON champions",achievements:["AFCON champions five times between 1984 and 2017","First African men’s team to reach a World Cup quarter-final","Olympic men’s gold at Sydney 2000","Record African men’s World Cup appearances through 2022"],current:[{name:"André Onana",note:"Goalkeeper · Cameroon international"},{name:"Bryan Mbeumo",note:"Forward · Cameroon international"},{name:"Carlos Baleba",note:"Midfielder · Cameroon international"}],legends:[{name:"Samuel Eto’o",note:"Four-time African Footballer of the Year"},{name:"Roger Milla",note:"1990 World Cup icon"},{name:"Rigobert Song",note:"Four-time men’s World Cup player"}]},
  CI: {team:"The Elephants",confederation:"CAF · WAFU",badge:"CI",worldCup:"Men: three consecutive finals from 2006 to 2014",continental:"Men: 3× AFCON champions",achievements:["AFCON champions in 1992, 2015 and 2023","Won AFCON 2023 on home soil","Qualified for three consecutive World Cups","ASEC Mimosas developed generations of elite players"],current:[{name:"Simon Adingra",note:"Winger · Côte d’Ivoire international"},{name:"Franck Kessié",note:"Midfielder · national-team captaincy group"},{name:"Oumar Diakité",note:"Forward · Côte d’Ivoire international"}],legends:[{name:"Didier Drogba",note:"Two-time African Footballer of the Year"},{name:"Yaya Touré",note:"Four-time African Footballer of the Year"},{name:"Didier Zokora",note:"Long-serving national-team midfielder"}]},
};

export const notableRoles: Record<string, string> = {
  "Omah Lay":"Singer-songwriter · global Afrobeats voice",
  "Chimamanda Ngozi Adichie":"Novelist and essayist",
  "Burna Boy":"Grammy-winning recording artist",
  "Hakeem Olajuwon":"Basketball Hall of Famer",
  "Wole Soyinka":"Nobel Prize-winning playwright",
  "Ngozi Okonjo-Iweala":"Economist and international leader",
  "Pelé":"Three-time World Cup-winning footballer",
  "Mohamed Salah":"Footballer and Egypt captain",
  "Kylian Mbappé":"Footballer and France captain",
  "Hayao Miyazaki":"Animation filmmaker and co-founder of Studio Ghibli",
  "Nelson Mandela":"Anti-apartheid leader and former president",
};

export const nigeriaFieldNotes = [
  {title:"A federation of enormous scale",text:"Nigeria is organised into 36 states and the Federal Capital Territory. Its population is larger than that of any other African country, while Lagos operates as one of the continent’s largest urban and commercial systems."},
  {title:"More than one Nigeria",text:"Hundreds of ethnic communities and languages coexist across the country. Hausa, Yoruba and Igbo are among the most widely spoken Nigerian languages, while English is the official language used across federal institutions."},
  {title:"A global sound laboratory",text:"Afrobeats, highlife, juju, fuji and many local traditions connect Nigerian cities to global audiences. Artists including Fela Kuti, Burna Boy, Wizkid, Tems and Omah Lay have helped reshape contemporary popular music."},
  {title:"Nollywood’s production engine",text:"Nigeria’s screen industry built a vast audience through resourceful, fast-moving production and direct distribution. Today its films and series travel across Africa and a worldwide diaspora."},
  {title:"From rainforest to Sahel",text:"The country stretches from mangrove-lined Atlantic coasts and the Niger Delta through forest and savanna to the drier landscapes around Lake Chad, creating sharp environmental contrasts."},
  {title:"A young, inventive economy",text:"Oil remains economically important, but technology, finance, entertainment, agriculture and small enterprise shape everyday activity. Lagos is a major African startup and creative-industry centre."},
  {title:"Kingdoms before the republic",text:"Benin, Oyo, Kanem-Bornu, Nri and other states developed sophisticated political and artistic traditions long before British colonial rule. Their histories remain central to modern regional identities."},
  {title:"Food that travels",text:"Jollof rice, suya, egusi soup, moi moi, pepper soup and countless regional dishes form one of Africa’s most recognisable culinary traditions—accompanied by a famously energetic debate about the best jollof."},
];
