"use client";

import {useState} from "react";
import Link from "next/link";
import {atlasByCode, atlasCountries} from "../atlas-data";

type Entry = {code:string; name:string; flag:string; value:string; score:number; note?:string; slug?:string};
export type Category = {id:string; short:string; title:string; eyebrow:string; unit:string; date:string; description:string; source:string; sourceLabel:string; caution?:string; entries:Entry[]};
const entry = (code:string, name:string, flag:string, value:string, score:number, note?:string, slug?:string):Entry => ({code,name,flag,value,score,note,slug});

const largest = [...atlasCountries].sort((a,b) => b.area-a.area).slice(0,10).map((country) => entry(country.code,country.name,country.flag,country.areaLabel,country.area,"Total area",country.slug));

export const rankingCategories: Category[] = [
  {id:"economies",short:"Richest",title:"Largest economies",eyebrow:"Economic scale",unit:"Nominal GDP · current US$",date:"IMF WEO · 2026 estimate",description:"Total output measures the size of an economy, not how evenly prosperity is shared. Values are rounded to make comparison readable.",source:"https://data.imf.org/en",sourceLabel:"IMF World Economic Outlook",entries:[entry("US","United States","🇺🇸","≈ $31.8T",31.8),entry("CN","China","🇨🇳","≈ $20.7T",20.7),entry("DE","Germany","🇩🇪","≈ $5.0T",5.0),entry("IN","India","🇮🇳","≈ $4.5T",4.5),entry("JP","Japan","🇯🇵","≈ $4.5T",4.45),entry("GB","United Kingdom","🇬🇧","≈ $4.0T",4.0),entry("FR","France","🇫🇷","≈ $3.4T",3.4),entry("IT","Italy","🇮🇹","≈ $2.6T",2.6),entry("RU","Russia","🇷🇺","≈ $2.5T",2.5),entry("CA","Canada","🇨🇦","≈ $2.4T",2.4)]},
  {id:"per-capita",short:"Per person",title:"Highest income per person",eyebrow:"Average economic output",unit:"GDP per capita · current US$",date:"World Bank · 2024",description:"GDP per person divides national output by population. It is not a salary and does not describe inequality or household wealth.",source:"https://data.worldbank.org/indicator/NY.GDP.PCAP.CD",sourceLabel:"World Bank national accounts",caution:"Microstates and financial centres can rank unusually high because of small resident populations and cross-border activity.",entries:[entry("MC","Monaco","🇲🇨","≈ $288,000",288000),entry("LI","Liechtenstein","🇱🇮","≈ $206,000",206000),entry("LU","Luxembourg","🇱🇺","≈ $137,000",137000),entry("IE","Ireland","🇮🇪","≈ $112,000",112000),entry("CH","Switzerland","🇨🇭","≈ $104,000",104000),entry("SG","Singapore","🇸🇬","≈ $90,700",90700),entry("NO","Norway","🇳🇴","≈ $86,800",86800),entry("US","United States","🇺🇸","≈ $84,500",84500),entry("IS","Iceland","🇮🇸","≈ $82,700",82700),entry("QA","Qatar","🇶🇦","≈ $76,700",76700)]},
  {id:"population",short:"Population",title:"Most populous nations",eyebrow:"People and scale",unit:"Estimated residents",date:"UN WPP 2024 · mid-2025",description:"Population estimates are demographic models, not a single-day headcount. Values below are rounded from the UN’s latest revision.",source:"https://population.un.org/wpp/",sourceLabel:"UN World Population Prospects",entries:[entry("IN","India","🇮🇳","1.464B",1464),entry("CN","China","🇨🇳","1.416B",1416),entry("US","United States","🇺🇸","347M",347),entry("ID","Indonesia","🇮🇩","286M",286),entry("PK","Pakistan","🇵🇰","255M",255),entry("NG","Nigeria","🇳🇬","238M",238),entry("BR","Brazil","🇧🇷","213M",213),entry("BD","Bangladesh","🇧🇩","176M",176),entry("RU","Russia","🇷🇺","144M",144),entry("ET","Ethiopia","🇪🇹","135M",135)]},
  {id:"football",short:"Football",title:"Football power ranking",eyebrow:"Current men’s national teams",unit:"Official world position",date:"FIFA · 20 July 2026",description:"A current form table based on FIFA’s official men’s ranking after the 2026 international cycle. Rankings move whenever rated matches are played.",source:"https://www.fifa.com/en/articles/spain-top-ranking-norway-big-gains",sourceLabel:"FIFA/Coca-Cola Men’s World Ranking",entries:[entry("ES","Spain","🇪🇸","World No. 1",10),entry("AR","Argentina","🇦🇷","World No. 2",9),entry("FR","France","🇫🇷","World No. 3",8),entry("GB","England","🏴","World No. 4",7,undefined,"united-kingdom"),entry("BR","Brazil","🇧🇷","World No. 5",6),entry("MA","Morocco","🇲🇦","World No. 6",5),entry("PT","Portugal","🇵🇹","World No. 7",4),entry("BE","Belgium","🇧🇪","World No. 8",3),entry("NL","Netherlands","🇳🇱","World No. 9",2),entry("MX","Mexico","🇲🇽","World No. 10",1)]},
  {id:"legacy",short:"World Cups",title:"Men’s World Cup legacy",eyebrow:"All-time champions",unit:"Senior men’s titles",date:"FIFA · through 2022",description:"The nations with the most FIFA Men’s World Cup victories. Equal title totals share the same historic achievement even when displayed sequentially.",source:"https://www.fifa.com/en/tournaments/mens/worldcup",sourceLabel:"FIFA World Cup archive",entries:[entry("BR","Brazil","🇧🇷","5 titles",5,"1958 · 1962 · 1970 · 1994 · 2002"),entry("DE","Germany","🇩🇪","4 titles",4,"1954 · 1974 · 1990 · 2014"),entry("IT","Italy","🇮🇹","4 titles",4,"1934 · 1938 · 1982 · 2006"),entry("AR","Argentina","🇦🇷","3 titles",3,"1978 · 1986 · 2022"),entry("FR","France","🇫🇷","2 titles",2,"1998 · 2018"),entry("UY","Uruguay","🇺🇾","2 titles",2,"1930 · 1950"),entry("GB","England","🏴","1 title",1,"1966", "united-kingdom"),entry("ES","Spain","🇪🇸","1 title",1,"2010")]},
  {id:"low-income",short:"Lowest income",title:"Lowest reported income per person",eyebrow:"Development pressure",unit:"GDP per capita · current US$",date:"World Bank · latest 2023–24",description:"This table describes low average economic output—not the worth, culture or potential of a country or its people. Conflict and missing data make exact ordering difficult.",source:"https://data.worldbank.org/indicator/NY.GDP.PCAP.CD?view=map",sourceLabel:"World Bank national accounts",caution:"Countries with unavailable or non-comparable recent observations are excluded. Values are rounded and should be read alongside poverty, prices and inequality data.",entries:[entry("BI","Burundi","🇧🇮","≈ $220",220),entry("CF","Central African Republic","🇨🇫","≈ $520",520),entry("MW","Malawi","🇲🇼","≈ $525",525),entry("MG","Madagascar","🇲🇬","≈ $545",545),entry("CD","DR Congo","🇨🇩","≈ $650",650),entry("MZ","Mozambique","🇲🇿","≈ $657",657),entry("NE","Niger","🇳🇪","≈ $735",735),entry("SL","Sierra Leone","🇸🇱","≈ $806",806),entry("LR","Liberia","🇱🇷","≈ $846",846),entry("GM","The Gambia","🇬🇲","≈ $908",908)]},
  {id:"integrity",short:"Integrity risk",title:"Highest perceived corruption risk",eyebrow:"Public-sector integrity",unit:"CPI score · 0–100",date:"Transparency International · CPI 2025",description:"The Corruption Perceptions Index measures perceived public-sector corruption. A lower score means higher perceived corruption; it does not label a population or measure every kind of corruption.",source:"https://www.transparency.org/en/cpi/2025",sourceLabel:"Transparency International CPI 2025",caution:"Perception-based indicators are comparative signals, not verdicts. Weak institutions, conflict and restricted civic space often overlap with low scores.",entries:[entry("SS","South Sudan","🇸🇸","9 / 100",9),entry("SO","Somalia","🇸🇴","9 / 100",9),entry("VE","Venezuela","🇻🇪","10 / 100",10),entry("ER","Eritrea","🇪🇷","13 / 100",13),entry("LY","Libya","🇱🇾","13 / 100",13),entry("YE","Yemen","🇾🇪","13 / 100",13),entry("NI","Nicaragua","🇳🇮","14 / 100",14),entry("SY","Syria","🇸🇾","15 / 100",15),entry("SD","Sudan","🇸🇩","15 / 100",15),entry("HT","Haiti","🇭🇹","16 / 100",16)]},
  {id:"territory",short:"Territory",title:"Largest countries by area",eyebrow:"Physical scale",unit:"Total area",date:"ISO-linked geographic record",description:"The largest sovereign states in TerraScope’s complete 195-country geographic dataset, using total-area reference figures.",source:"https://github.com/mledoze/countries",sourceLabel:"world-countries reference dataset",entries:largest},
];

function countryHref(item:Entry) {
  if (item.slug) return `/countries/${item.slug}`;
  return `/countries/${atlasByCode.get(item.code)?.slug ?? ""}`;
}

export default function RankingsExplorer({initialCategory="economies",detail=false}:{initialCategory?:string;detail?:boolean}) {
  const [active, setActive] = useState(rankingCategories.some((item)=>item.id===initialCategory)?initialCategory:rankingCategories[0].id);
  const category = rankingCategories.find((item) => item.id === active) ?? rankingCategories[0];
  const max = Math.max(...category.entries.map((item) => item.score));
  return <section className="ranking-explorer">
    <div className="ranking-tabs" role="tablist" aria-label="World ranking categories">{rankingCategories.map((item) => <button type="button" role="tab" aria-selected={item.id === active} className={item.id === active ? "active" : ""} key={item.id} onClick={() => setActive(item.id)}><span>{item.short}</span><small>{item.entries.length}</small></button>)}</div>
    <div className="ranking-dashboard">
      <header><div><p>{category.eyebrow}</p><h2>{category.title}</h2></div><div><small>{category.unit}</small><b>{category.date}</b></div></header>
      <p className="ranking-description">{category.description}</p>
      <div className="ranking-table">{category.entries.map((item,index) => <Link href={countryHref(item)} className="ranking-row" key={`${category.id}-${item.name}`}>
        <span className="ranking-position">{String(index + 1).padStart(2,"0")}</span><span className="ranking-flag">{item.flag}</span><div><b>{item.name}</b>{item.note && <small>{item.note}</small>}</div><strong>{item.value}</strong><i style={{width:`${Math.max(4,(item.score/max)*100)}%`}} />
      </Link>)}</div>
      <footer className="ranking-method"><div><span>Source</span><a href={category.source} target="_blank" rel="noreferrer">{category.sourceLabel} ↗</a></div><div className="ranking-footer-actions">{category.caution && <p>{category.caution}</p>}{!detail&&<Link href={`/rankings/${category.id}`}>Open dedicated {category.short.toLowerCase()} page →</Link>}</div></footer>
    </div>
  </section>;
}
