"use client";
import {useState,type ReactNode} from "react";
import Link from "next/link";
import worldMap from "@svg-maps/world";
import {atlasByCode,atlasCountries} from "../atlas-data";
import {SiteHeader} from "../components/SiteHeader";
import {SiteFooter} from "../components/SiteFooter";
type Lens="population"|"area"|"travel";type WorldMapLocation={id:string;path:string};
const population=[["IN","India","1.464B",1464],["CN","China","1.416B",1416],["US","United States","347M",347],["ID","Indonesia","286M",286],["PK","Pakistan","255M",255],["NG","Nigeria","238M",238]] as const;
const area=[...atlasCountries].sort((a,b)=>b.area-a.area).slice(0,6).map((country)=>[country.code,country.name,country.areaLabel,country.area] as const);
const travel=[["FR","France","102M arrivals",102],["ES","Spain","93.8M arrivals",93.8],["US","United States","72.4M arrivals",72.4],["TR","Türkiye","60.6M arrivals",60.6],["IT","Italy","57.9M arrivals",57.9],["MX","Mexico","45M arrivals",45]] as const;
const lenses={population,area,travel};const byMapId=new Map(atlasCountries.map((country)=>[country.code.toLowerCase(),country]));
export default function WorldDashboard({children}:{children?:ReactNode}){const [lens,setLens]=useState<Lens>("population");const rows=lenses[lens];const max=Math.max(...rows.map((row)=>Number(row[3])));return <><SiteHeader active="rankings"/><section className="rankings-hero"><div><p className="eyebrow"><span/>World rankings · sourced comparisons</p><h1>See the world<br/><em>in relation.</em></h1><p>Start with a quick global view, swipe across ranking lenses, then open a dedicated page for the full table and methodology.</p></div><aside><small>Travel guide connection</small><b>Rank → understand → plan</b><p>Every country row opens its full profile, with government, history and practical trip-planning notes together.</p><Link href="/rankings/most-visited">Open travel rankings →</Link></aside></section><section className="rankings-overview" aria-label="World ranking overview"><div className="rankings-stat-strip"><article><small>Countries</small><b>195</b><span>complete profiles</span></article><article><small>World population</small><b>8.2B</b><span>rounded estimate</span></article><article><small>Ranking lenses</small><b>10</b><span>with sources</span></article><article><small>World regions</small><b>5</b><span>atlas chapters</span></article></div><div className="rankings-world-card"><div className="rankings-map"><header><small>Complete atlas coverage</small><b>195 sovereign states</b></header><svg viewBox={worldMap.viewBox} role="img" aria-label="Map of countries included in TerraScope rankings">{(worldMap.locations as WorldMapLocation[]).map((location)=><path key={location.id} d={location.path} className={byMapId.has(location.id)?"included":"territory"}/>)}</svg><Link href="/countries">Browse the full atlas →</Link></div><aside className="rankings-mini-list"><header><div><small>Quick lens</small><h2>{lens==="population"?"Population":lens==="area"?"Territory":"Visitor arrivals"}</h2></div><select aria-label="Choose quick ranking lens" value={lens} onChange={(event)=>setLens(event.target.value as Lens)}><option value="population">Population</option><option value="area">Area</option><option value="travel">Travel</option></select></header>{rows.map((row,index)=>{const country=atlasByCode.get(row[0]);return <Link href={`/countries/${country?.slug??""}`} key={row[0]}><span>{String(index+1).padStart(2,"0")}</span><i>{country?.flag}</i><div><p><b>{row[1]}</b><strong>{row[2]}</strong></p><em><u style={{width:`${Math.max(8,Number(row[3])/max*100)}%`}}/></em></div></Link>})}<Link className="rankings-mini-more" href="#all-rankings">Explore every ranking lens →</Link></aside></div></section>{children}<SiteFooter/></>}
